--LAB3 CALIFICADA 2020-2

--PREGUNTA 1: MOSTRAR LA CANTIDAD DE POSTULANTES VARONES PROVENIENTES DE CADA CENTRO DE ESTUDIOS
SELECT * FROM SP_POSTULANTE;
SELECT * FROM SP_USUARIO;
SELECT * FROM SP_POSTULANTE_CENTRO;
SELECT * FROM SP_CENTRO_ESTUDIOS;
--COMO TENGO QUE REALIZAR UNA FUNCION EN UNA FILA, SERÁ GROUP BY
SELECT C.NOMBRE , COUNT(*) AS CANTIDAD_POSTULANTES_VARONES
FROM SP_POSTULANTE P, SP_USUARIO U, SP_POSTULANTE_CENTRO PC, SP_CENTRO_ESTUDIOS C
WHERE pc.id_postulante = p.id_postulante
AND u.id_usuario = p.id_usuario
AND pc.id_centro = c.id_centro
AND U.SEXO = 'M'
GROUP BY C.NOMBRE
ORDER BY COUNT(*) DESC;

--PREGUNTA 2: MOSTRAR LA CANT DE PAGOS Y MONTO TOTAL EN CADA BANCO SOLO SI DICHA CANT DE PAGO > 3
SELECT * FROM SP_PAGO;
SELECT * FROM SP_CUENTA;
--COMO TENGO QUE REALIZAR UNA FUNCION EN UNA FILA, SERÁ GROUP BY
SELECT C.BANCO, COUNT(*) AS CANTIDAD_PAGOS, SUM(MONTO) AS MONTO_TOTAL_PAGADO
FROM SP_PAGO P, SP_CUENTA C
WHERE p.id_cuenta = c.id_cuenta
GROUP BY C.BANCO
--AHORA TENGO QUE IMPRIMIR SOLO LOS QUE TIENEN CANT>3, ASI QUE EVALUO EL GRUPO
HAVING COUNT(*) > 3; 

--PREGUNTA 3: MOSTRAR LA CANT DE POST QUE PRESENTARON CADA TIPO DE DOCUMENTO(GROUP BY)
--CONSIDERAR SOLO QUIENES NACIERON EN AÑO%2==0, ORDENAR DESC POR CANT
SELECT * FROM SP_POSTULANTE;
SELECT * FROM SP_DOCUMENTO_POSTULANTE;
SELECT * FROM SP_DOCUMENTO;
--COMO TENGO QUE REALIZAR UNA FUNCION EN UNA FILA, SERÁ GROUP BY
SELECT D.NOMBRE AS NOMBRE_DE_DOCUMENTO , COUNT(*) AS CANTIDAD_POSTULANTES
FROM SP_POSTULANTE P, SP_DOCUMENTO_POSTULANTE DP, SP_DOCUMENTO D
WHERE p.id_postulante = dp.id_postulante
AND dp.id_documento = d.id_documento
AND MOD(EXTRACT(YEAR FROM P.FECHA_NACIMIENTO),2) = 0 --VALIDO QUE SEA AÑO PAR
GROUP BY D.NOMBRE
ORDER BY COUNT(*) DESC;

--PREGUNTA 4: MOSTRAR APELLIDO Y NOMBRE DE LOS POSTULANTES QUE PARTICIPARON EN MISMA CONV QUE "JORGE".
--TAMBIEN MOSTRAR EL NOMBRE DE LA CONVOCATORIA
SELECT * FROM SP_POSTULANTE;
SELECT * FROM SP_USUARIO;
SELECT * FROM SP_CONVOCATORIA_POSTULANTE;
SELECT * FROM SP_CONVOCATORIA;
--PARA ESTE CASO COMO NO ME DAN NINGUNA CLAUSULA Y TODAS LAS FILAS SE IMPRIMEN NORMAL
--AL MOMENTO DE COMPARAR LO TENDRÉ QUE REALIZAR POR UNA SUBCONSULTA
SELECT U.AP_PATERNO||' '||U.AP_MATERNO||' '||U.NOMBRE AS POSTULANTE, C.NOMBRE AS NOMBRE_CONVOCATORIA
FROM SP_POSTULANTE P, SP_USUARIO U, SP_CONVOCATORIA_POSTULANTE CP, SP_CONVOCATORIA C
WHERE p.id_postulante = cp.id_postulante
AND cp.id_convocatoria = c.id_convocatoria
AND u.id_usuario = p.id_usuario
AND CP.ID_CONVOCATORIA IN (SELECT C.ID_CONVOCATORIA
                           FROM SP_POSTULANTE P, SP_USUARIO U, SP_CONVOCATORIA_POSTULANTE CP, SP_CONVOCATORIA C
                           WHERE P.ID_POSTULANTE = CP.ID_POSTULANTE
                           AND cp.id_convocatoria = c.id_convocatoria
                           AND u.id_usuario = p.id_usuario
                           AND U.NOMBRE = 'Jorge' AND U.AP_PATERNO = 'Talledo');

--PREGUNTA 5: MOSTRAR APELLIDOS Y NOMBRE Y FECHA_NAC DEL POST DE MAYOR EDAD. 
--TAMBIEN MOSTRAR EL NOMBRE DE SU APODERADO
SELECT * FROM SP_POSTULANTE; -- FECHA_NAC -> MAYOR EDAD ES FECHA MAS ANTIGUA -> MIN
SELECT * FROM SP_USUARIO; --APELLIDO + NOMBRE
SELECT * FROM SP_APODERADO; --NOMBRE_APOD
--COMO NO ESTOY IMPRIMIENDO EN LAS FILAS UNA FUNCION(MIN,MAX,COUNT,ETC) Y TENGO Q HALLAR EL MIN, SERÁ SUBCONSULTA
SELECT U.AP_PATERNO, U.AP_MATERNO, U.NOMBRE, P.FECHA_NACIMIENTO, A.NOMBRE_COMPLETO AS APODERADO
FROM SP_POSTULANTE P, SP_USUARIO U, SP_APODERADO A
WHERE p.id_postulante = a.id_postulante
AND u.id_usuario = p.id_usuario
AND P.FECHA_NACIMIENTO = (SELECT MIN(FECHA_NACIMIENTO)
                           FROM SP_POSTULANTE);

--PREGUNTA 6: MOSTRAR APELLIDO + NOMBRE DE LOS POST QUE REALIZARON PAGO MENOR O IGUAL AL MONTO PROM (FUNCION)
--SI SOLO ME PIDIERON EL MONTO PROMEDIO PODRIA REALIZARSE POR GROUP BY, PERO COMO ME DAN CONDICION SERÁ POR SUBCONSULTA
--TAMBIEN MOSTRAR MONTO Y NOMBRE DEL BANCO DONDE SE REALIZÓ
SELECT * FROM SP_POSTULANTE;--ID_USUARIO
SELECT * FROM SP_USUARIO; --NOMBRE, APELLIDOS
SELECT * FROM SP_PAGO; --MONTO
SELECT * FROM SP_CUENTA; --BANCO

SELECT U.AP_PATERNO, U.AP_MATERNO, U.NOMBRE, PG.MONTO , C.BANCO
FROM SP_POSTULANTE P, SP_USUARIO U, SP_PAGO PG, SP_CUENTA C
WHERE u.id_usuario = p.id_usuario
AND pg.id_postulante = p.id_postulante
AND pg.id_cuenta = c.id_cuenta
AND PG.MONTO <= (SELECT AVG(MONTO)
                 FROM SP_PAGO);
