CREATE TABLE ET_BUS (
    ID_BUS        NUMBER NOT NULL,
    ID_MODELO_BUS NUMBER NOT NULL,
    PLACA         VARCHAR2(7 BYTE) NOT NULL,
    ASEGURADO     NUMBER(1) NOT NULL,
    ESTADO        CHAR(1 BYTE) NOT NULL
);

COMMENT ON COLUMN ET_BUS.ID_BUS IS
    'IDENTIFICADOR DEL BUS.';

COMMENT ON COLUMN ET_BUS.ID_MODELO_BUS IS
    'IDENTIFICADOR DEL MODELO.';

COMMENT ON COLUMN ET_BUS.PLACA IS
    'NUMERO DE PLACA.';

COMMENT ON COLUMN ET_BUS.ASEGURADO IS
    '0: NO ASEGURADO, 1: ASEGURADO.';

COMMENT ON COLUMN ET_BUS.ESTADO IS
    'A: ACTIVO, D: EN DESUSO, M: EN MANTENIMIENTO.';

ALTER TABLE ET_BUS ADD CONSTRAINT BUS_PK PRIMARY KEY ( ID_BUS );

CREATE TABLE ET_CONDUCTOR (
    ID_CONDUCTOR     NUMBER NOT NULL,
    NOMBRES          VARCHAR2(50 BYTE) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(50 BYTE) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(50 BYTE) NOT NULL,
    TIPO_LICENCIA    VARCHAR2(10 BYTE) NOT NULL,
    ESTADO           CHAR(1 BYTE) NOT NULL
);

COMMENT ON COLUMN ET_CONDUCTOR.ID_CONDUCTOR IS
    'IDENTIFICADOR DEL CONDUCTOR.';

COMMENT ON COLUMN ET_CONDUCTOR.NOMBRES IS
    'NOMBRES.';

COMMENT ON COLUMN ET_CONDUCTOR.APELLIDO_PATERNO IS
    'APELLIDO PATERNO.';

COMMENT ON COLUMN ET_CONDUCTOR.APELLIDO_MATERNO IS
    'APELLIDO MATERNO.';

COMMENT ON COLUMN ET_CONDUCTOR.TIPO_LICENCIA IS
    'TIPO DE LICENCIA DE CONDUCIR.';

COMMENT ON COLUMN ET_CONDUCTOR.ESTADO IS
    'A: ACTIVO, S: SUSPENDIDO, B: DADO DE BAJA, R: RETIRADO.';

ALTER TABLE ET_CONDUCTOR ADD CONSTRAINT CONDUCTOR_PK PRIMARY KEY ( ID_CONDUCTOR );

CREATE TABLE ET_DISTRITO (
    ID_DISTRITO CHAR(6 BYTE) NOT NULL,
    NOMBRE      VARCHAR2(100 BYTE) NOT NULL
);

COMMENT ON COLUMN ET_DISTRITO.ID_DISTRITO IS
    'IDENTIFICADOR UBIGEO DEL DISTRITO.';

COMMENT ON COLUMN ET_DISTRITO.NOMBRE IS
    'NOMBRE DEL DISTRITO.';

ALTER TABLE ET_DISTRITO ADD CONSTRAINT DISTRITO_PK PRIMARY KEY ( ID_DISTRITO );

CREATE TABLE ET_MATRIZ_PAGO (
    ID_PARADERO_INICIAL NUMBER NOT NULL,
    ID_PARADERO_FINAL   NUMBER NOT NULL,
    PRECIO              NUMBER(6, 2) NOT NULL
);

COMMENT ON COLUMN ET_MATRIZ_PAGO.ID_PARADERO_INICIAL IS
    'IDENTIFICADOR DEL PARADERO INICIAL.';

COMMENT ON COLUMN ET_MATRIZ_PAGO.ID_PARADERO_FINAL IS
    'IDENTIFICADOR DEL PARADERO FINAL.';

COMMENT ON COLUMN ET_MATRIZ_PAGO.PRECIO IS
    'PRECIO DEL VIAJE ENTRE EL PARADERO INICIAL Y FINAL.';

ALTER TABLE ET_MATRIZ_PAGO ADD CONSTRAINT MATRIZ_PAGO_PK PRIMARY KEY ( ID_PARADERO_INICIAL,
                                                                       ID_PARADERO_FINAL );

CREATE TABLE ET_MODELO_BUS (
    ID_MODELO_BUS    NUMBER NOT NULL,
    MODELO           VARCHAR2(20 BYTE) NOT NULL,
    FABRICANTE       VARCHAR2(100 BYTE) NOT NULL,
    ANHO_FABRICACION NUMBER,
    MAX_VELOCIDAD    NUMBER,
    NUMERO_ASIENTOS  NUMBER,
    CAPACIDAD_DE_PIE NUMBER
);

COMMENT ON COLUMN ET_MODELO_BUS.ID_MODELO_BUS IS
    'IDENTIFICADOR DEL MODELO.';

COMMENT ON COLUMN ET_MODELO_BUS.MODELO IS
    'NOMBRE DEL MODELO.';

COMMENT ON COLUMN ET_MODELO_BUS.FABRICANTE IS
    'NOMBRE DE FABRICANTE.';

COMMENT ON COLUMN ET_MODELO_BUS.ANHO_FABRICACION IS
    'AÑO DE FABRICACIÓN.';

COMMENT ON COLUMN ET_MODELO_BUS.MAX_VELOCIDAD IS
    'MÁXIMA VELOCIDAD EN KM/H.';

COMMENT ON COLUMN ET_MODELO_BUS.NUMERO_ASIENTOS IS
    'NÚMERO DE PASAJEROS SENTADOS.';

COMMENT ON COLUMN ET_MODELO_BUS.CAPACIDAD_DE_PIE IS
    'NÚMERO DE PASAJEROS QUE PUEDEN IR DE PIE.';

ALTER TABLE ET_MODELO_BUS ADD CONSTRAINT MODELO_BUS_PK PRIMARY KEY ( ID_MODELO_BUS );

CREATE TABLE ET_PARADERO (
    ID_PARADERO NUMBER NOT NULL,
    NOMBRE      VARCHAR2(50 BYTE) NOT NULL,
    ID_DISTRITO CHAR(6 BYTE) NOT NULL,
    REFERENCIA  VARCHAR2(50 BYTE),
    TIPO        CHAR(1 BYTE) NOT NULL,
    ESTADO      CHAR(1 BYTE) NOT NULL
);

COMMENT ON COLUMN ET_PARADERO.ID_PARADERO IS
    'IDENTIFICADOR DEL PARADERO.';

COMMENT ON COLUMN ET_PARADERO.NOMBRE IS
    'NOMBRE DEL PARADERO.';

COMMENT ON COLUMN ET_PARADERO.ID_DISTRITO IS
    'IDENTIFICADOR UBIGEO DEL DISTRITO.';

COMMENT ON COLUMN ET_PARADERO.REFERENCIA IS
    'REFERENCIA DE LA DIRECCION DEL PARADERO.';

COMMENT ON COLUMN ET_PARADERO.TIPO IS
    'I: TERMINAL INICIAL DE RUTA, F: TERMINAL FIN DE RUTA, N: OTRO PARADERO';

COMMENT ON COLUMN ET_PARADERO.ESTADO IS
    'A: ACTUALMENTE SE USA, B: DADO DE BAJA, T: PARADERO REUBICADO TEMPORALMENTE';

ALTER TABLE ET_PARADERO ADD CONSTRAINT PARADERO_PK PRIMARY KEY ( ID_PARADERO );

CREATE TABLE ET_TICKET (
    ID_TICKET     NUMBER NOT NULL,
    ID_TURNO            NUMBER NOT NULL,
    ID_PARADERO_INICIAL NUMBER NOT NULL,
    ID_PARADERO_FINAL   NUMBER NOT NULL,
    PRECIO              NUMBER(6, 2) NOT NULL,
    FECHA_HORA_EMISION  TIMESTAMP NOT NULL,
    TIPO_PASAJE         CHAR(1 BYTE) NOT NULL
);

COMMENT ON COLUMN ET_TICKET.ID_TICKET IS
    'IDENTIFICADOR DEL TICKET.';

COMMENT ON COLUMN ET_TICKET.ID_TURNO IS
    'IDENTIFICADOR DEL TURNO.';

COMMENT ON COLUMN ET_TICKET.ID_PARADERO_INICIAL IS
    'IDENTIFICADOR DEL PARADERO INICIAL.';

COMMENT ON COLUMN ET_TICKET.ID_PARADERO_FINAL IS
    'IDENTIFICADOR DEL PARADERO FINAL.';

COMMENT ON COLUMN ET_TICKET.PRECIO IS
    'PRECIO DEL TICKET.';

COMMENT ON COLUMN ET_TICKET.FECHA_HORA_EMISION IS
    'FECHA Y HORA DE EMISIÓN.';

COMMENT ON COLUMN ET_TICKET.TIPO_PASAJE IS
    'N: PASAJE NORMAL, U: PASAJE MEDIO.';

ALTER TABLE ET_TICKET ADD CONSTRAINT ET_TICKET_PK PRIMARY KEY ( ID_TICKET );

CREATE TABLE ET_TURNO (
    ID_TURNO_VIAJE          NUMBER NOT NULL,
    ID_CONDUCTOR            NUMBER NOT NULL,
    ID_BUS                  NUMBER NOT NULL,
    HORA_PARTIDA            CHAR(4 BYTE),
    HORA_LLEGADA_PROGRAMADA CHAR(4 BYTE),
    HORA_LLEGADA_REAL       CHAR(4 BYTE),
    FECHA                   DATE NOT NULL,
    SENTIDO                 CHAR(1 BYTE) NOT NULL
);

COMMENT ON COLUMN ET_TURNO.ID_TURNO_VIAJE IS
    'IDENTIFICADOR DEL TURNO.';

COMMENT ON COLUMN ET_TURNO.ID_CONDUCTOR IS
    'IDENTIFICADOR DEL CONDUCTOR.';

COMMENT ON COLUMN ET_TURNO.ID_BUS IS
    'IDENTIFICADOR DEL BUS.';

COMMENT ON COLUMN ET_TURNO.HORA_PARTIDA IS
    'HORA DE PARTIDA EN FORMATO 24 HORAS (HHMM).';

COMMENT ON COLUMN ET_TURNO.HORA_LLEGADA_PROGRAMADA IS
    'HORA DE LLEGADA PROGRAMADA  EN FORMATO 24 HORAS (HHMM).';

COMMENT ON COLUMN ET_TURNO.HORA_LLEGADA_REAL IS
    'HORA DE LLEGADA REAL  EN FORMATO 24 HORAS (HHMM).';

COMMENT ON COLUMN ET_TURNO.SENTIDO IS
    'SENTIDO DEL TURNO. I: IDA, V: VUELTA.';

ALTER TABLE ET_TURNO ADD CONSTRAINT ET_TURNO_PK PRIMARY KEY ( ID_TURNO_VIAJE );

CREATE TABLE ET_TURNO_PARADERO (
    ID_TURNO         NUMBER NOT NULL,
    ID_PARADERO      NUMBER NOT NULL,
    HORA_LLEGADA     CHAR(4 BYTE),
    PASAJEROS_SUBIDA NUMBER,
    PASAJEROS_BAJADA NUMBER
);

COMMENT ON COLUMN ET_TURNO_PARADERO.ID_TURNO IS
    'IDENTIFICADOR DEL TURNO.';

COMMENT ON COLUMN ET_TURNO_PARADERO.ID_PARADERO IS
    'IDENTIFICADOR DEL PARADERO.';

COMMENT ON COLUMN ET_TURNO_PARADERO.HORA_LLEGADA IS
    'HORA DE LLEGADA EN FORMATO 24 HORAS (HHMM).';

COMMENT ON COLUMN ET_TURNO_PARADERO.PASAJEROS_SUBIDA IS
    'PASAJEROS QUE SUBEN.';

COMMENT ON COLUMN ET_TURNO_PARADERO.PASAJEROS_BAJADA IS
    'PASAJEROS QUE BAJAN.';

ALTER TABLE ET_TURNO_PARADERO ADD CONSTRAINT ET_TURNO_PARADERO_PK PRIMARY KEY ( ID_TURNO,
                                                                                ID_PARADERO );

ALTER TABLE ET_BUS
    ADD CONSTRAINT BUS_MOD_BUS_FK FOREIGN KEY ( ID_MODELO_BUS )
        REFERENCES ET_MODELO_BUS ( ID_MODELO_BUS );

ALTER TABLE ET_MATRIZ_PAGO
    ADD CONSTRAINT MAT_PAG_PAR_FK01 FOREIGN KEY ( ID_PARADERO_INICIAL )
        REFERENCES ET_PARADERO ( ID_PARADERO );

ALTER TABLE ET_MATRIZ_PAGO
    ADD CONSTRAINT MAT_PAG_PAR_FK02 FOREIGN KEY ( ID_PARADERO_FINAL )
        REFERENCES ET_PARADERO ( ID_PARADERO );

ALTER TABLE ET_PARADERO
    ADD CONSTRAINT PAR_DIS_FK FOREIGN KEY ( ID_DISTRITO )
        REFERENCES ET_DISTRITO ( ID_DISTRITO );

ALTER TABLE ET_TICKET
    ADD CONSTRAINT TIC_PAR_FK01 FOREIGN KEY ( ID_PARADERO_INICIAL )
        REFERENCES ET_PARADERO ( ID_PARADERO );

ALTER TABLE ET_TICKET
    ADD CONSTRAINT TIC_PAR_FK02 FOREIGN KEY ( ID_PARADERO_FINAL )
        REFERENCES ET_PARADERO ( ID_PARADERO );

ALTER TABLE ET_TICKET
    ADD CONSTRAINT TIC_TUR_FK FOREIGN KEY ( ID_TURNO )
        REFERENCES ET_TURNO ( ID_TURNO_VIAJE );

ALTER TABLE ET_TURNO
    ADD CONSTRAINT TUR_BUS_FK FOREIGN KEY ( ID_BUS )
        REFERENCES ET_BUS ( ID_BUS );

ALTER TABLE ET_TURNO
    ADD CONSTRAINT TUR_CON_FK FOREIGN KEY ( ID_CONDUCTOR )
        REFERENCES ET_CONDUCTOR ( ID_CONDUCTOR );

ALTER TABLE ET_TURNO_PARADERO
    ADD CONSTRAINT TUR_PAR_PAR_FK FOREIGN KEY ( ID_PARADERO )
        REFERENCES ET_PARADERO ( ID_PARADERO );

ALTER TABLE ET_TURNO_PARADERO
    ADD CONSTRAINT TUR_PAR_TUR_FK FOREIGN KEY ( ID_TURNO )
        REFERENCES ET_TURNO ( ID_TURNO_VIAJE );



