--LAB 2022.1

--PREGUNTA 1:
SELECT * FROM DEPARTAMENTOS;
SELECT * FROM HISTORIAL_LABORAL;

--como me dicen que se muestra por departamento(GROUP BY)
--ademas, piden cant empleados (COUNT)
SELECT A.NOMBRE_DPTO, COUNT(*) AS CANTIDAD
FROM DEPARTAMENTOS A, HISTORIAL_LABORAL B
WHERE A.DPTO_COD = B.DPTO_COD AND FECHA_FIN IS NULL
GROUP BY A.NOMBRE_DPTO;

--PREGUNTA 2:
--Ordenar alfabeticamente por el primer apellido --> muestra apellidos + nombres y dni
--Empleados del departamento MARKETING
SELECT * FROM EMPLEADOS;
SELECT * FROM HISTORIAL_LABORAL;
SELECT * FROM DEPARTAMENTOS;

SELECT E.APELLIDO1 || E.APELLIDO2 ||' , ' || E.NOMBRE , E.DNI
FROM EMPLEADOS E, HISTORIAL_LABORAL H , DEPARTAMENTOS D
--verifico que elementos comparten
WHERE h.dpto_cod = d.dpto_cod
AND D.NOMBRE_DPTO = 'MARKETING' -- UPPER('Marketing')
AND h.empleado_dni = E.DNI
AND H.FECHA_FIN IS NULL
ORDER BY APELLIDO1 ASC;

--PREGUNTA 3:
SELECT * FROM DEPARTAMENTOS;
SELECT * FROM EMPLEADOS;
SELECT * FROM HISTORIAL_LABORAL;
SELECT * FROM HISTORIAL_SALARIAL;
--Lista empleados ordenada por departamento y por saladio de desc
--Además, me dice que estan trabajando actualmente, por lo tanto no tendran fecha fin
SELECT D.NOMBRE_DPTO , E.APELLIDO1, E.APELLIDO2, E.NOMBRE, E.DNI, HS.SALARIO
FROM DEPARTAMENTOS D, EMPLEADOS E, HISTORIAL_LABORAL HL, HISTORIAL_SALARIAL HS
WHERE hl.dpto_cod = d.dpto_cod
AND hs.empleado_dni = hl.empleado_dni
AND e.dni = hs.empleado_dni
AND hs.fecha_fin is NULL AND hl.fecha_fin IS NULL
ORDER BY D.DPTO_COD, hs.SALARIO DESC;

--PREGUNTA 4:
--Lista de los departamentos (Agrupar por departamentos) + cantidadEmpleados POR DEPARTAMENTO y el promSalario
SELECT * FROM HISTORIAL_LABORAL;
SELECT * FROM DEPARTAMENTOS;
SELECT * FROM HISTORIAL_SALARIAL;

SELECT D.NOMBRE_DPTO , COUNT (*) AS CANTIDAD , ROUND(AVG(HS.SALARIO),2) AS PROMEDIO_DPTO
FROM HISTORIAL_LABORAL HL, DEPARTAMENTOS D, HISTORIAL_SALARIAL HS
WHERE hs.fecha_fin IS NULL AND hl.fecha_fin IS NULL
AND HL.EMPLEADO_DNI = HS.EMPLEADO_DNI
AND hl.dpto_cod = d.dpto_cod
GROUP BY D.NOMBRE_DPTO
ORDER BY PROMEDIO_DPTO DESC;

--PREGUNTA 5:
--AUMENTE EN 250 SOLES EL SALARIO DEL ULTIMO TRABAJO QUE TIENEN MAS DE 1 ESTUDIO
SELECT * FROM HISTORIAL_SALARIAL;

UPDATE HISTORIAL_SALARIAL 
SET SALARIO = SALARIO + 250
WHERE fecha_fin IS NULL AND EMPLEADO_DNI || TO_CHAR(FECHA_COMIENZO,'DD/MM/YYYY')
IN (
SELECT X.EMPLEADO_DNI || TO_CHAR(FECHA_COMIENZO,'DD/MM/YYYY')
FROM (
     SELECT EMPLEADO_DNI, COUNT(*) AS CANT
     FROM ESTUDIOS
     GROUP BY EMPLEADO_DNI) X, HISTORIAL_SALARIAL S
WHERE S.EMPLEADO_DNI = X.EMPLEADO_DNI
AND S.FECHA_FIN IS NULL AND X.CANT>1);

--HALLO LOS EMPLEADOS CON LA CANTIDAD DE ESTUDIOS QUE POSEEN
SELECT EMPLEADO_DNI, COUNT(*) AS CANT
FROM ESTUDIOS
GROUP BY EMPLEADO_DNI;

--ME DA LA CONCATENACION DE LA NUEVA TABLA CREADA QUE MUESTRA LA CANTIDAD DE ESTUDIOS QUE POSEEN LOS EMPLEADOS
SELECT X.EMPLEADO_DNI || TO_CHAR(FECHA_COMIENZO,'DD/MM/YYYY')
FROM (
     SELECT EMPLEADO_DNI, COUNT(*) AS CANT
     FROM ESTUDIOS
     GROUP BY EMPLEADO_DNI)X, HISTORIAL_SALARIAL S;

--METODO:
--PRIMERO ACTUALIZO LOS DATOS DE LA TABLA HISTORIAL_SALARIAL
--DESPUES COMENTO QUE COLUMNA VOY A ACTUALIZAR
--SE ACTUALIZA SOLO AQUELLOS QUE SIGUEN TRABAJANDO Y VERIFICO QUE ALGUN VALOR CONCATENADO COINCIDA CON ALGUN VALOR DE LA SUBCONSULTA
--CREO UNA LISTA QUE CUMPLA LAS CONDICIONES
--CREO OTRA TABLA QUE CUENTE LOS EMPLEADOS DE LA TABLA ESTUDIOS, AGRUPARLOS E IR SUMANDO --> TABLA X
--VERIFICO QUE LOS DNIS COINCIDAN
--Y POR ULTIMO EL NUMERO DE VECES QUE APARECE CADA VALOR DE EMPLEADOS DEBE SER MAYOR A 1

--PREGUNTA 6: ELIMINA EL ULTIMO REGISTRO DE TRABAJO DEL SUPERVISOR(SUP) QUE 
--ESTUDIÓ EN LA UNIVERSIDAD NACIONAL SAN AGUSTIN
DELETE FROM HISTORIAL_LABORAL
WHERE EMPLEADO_DNI || TRAB_COD || FECHA_INICIO = (--CONSULTA PRINCIPAL
		SELECT H.EMPLEADO_DNI || H.TRAB_COD || H.FECHA_INICIO
		FROM HISTORIAL_LABORAL H , ESTUDIOS E
		WHERE H.FECHA_FIN IS NULL
		AND  E.EMPLEADO_DNI = H.EMPLEADO_DNI
		AND H.SUPERVISOR_DNI IS NOT NULL
		AND GRADO = 'SUP'
		AND E.UNIVERSIDAD IN (--SUBCONSULTA
					SELECT U.UNIV_COD
					FROM UNIVERSIDADES UB2
					WHERE U.NOMBRE_UNIV = 'Nacional San Agustin');
		
		

--PREGUNTA 7:


