--SOLUCIÓN EXAMEN PARCIAL 2022-2

--PREGUNTA 3:

--A) LISTAR EL TOTAL DE VENTAS DE LOS MEDICAMENTOS QUE CONTENGA EN SU DESCRIPCION "FORTE"
--DURANTE LOS MESES DE ABRIL A SETIEMBRE. ORDENADA DESC POR EL MONTO TOTAL DE VENTAS

--PLANTEAMIENTO : MONTON TOTAL --> SUM(VENTAS)
SELECT * FROM EE1_MEDICAMENTO; -- DESCRIPCIONMED + PRECIO
SELECT * FROM EE1_DETALLE_VENTA; -- PRECIOUNITARIO + PRECIOTOTAL + CANTIDAD
SELECT * FROM EE1_VENTA; -- MONTO TOTAL POR FECHA

SELECT M.DESCRIPCIONMED , V.MONTOTOTAL
FROM EE1_DETALLE_VENTA D, EE1_MEDICAMENTO M, EE1_VENTA V
WHERE m.idmedicamento = d.idmedicamento AND v.idventa = d.idventa;

--AHORA SACO TODAS Y VERIFICO QUE EL MEDICAMENTO POSEA NICK FORTE
SELECT D.IDMEDICAMENTO, M.DESCRIPCIONMED, SUM(D.PRECIOTOTAL) AS MONTOTOTAL
FROM EE1_DETALLE_VENTA D, EE1_MEDICAMENTO M, EE1_VENTA V
WHERE m.idmedicamento = d.idmedicamento AND v.idventa = d.idventa
AND TO_CHAR(V.FECHAVENTA,'MM') BETWEEN '04' AND '09'
AND M.DESCRIPCIONMED LIKE '%FORTE%'
GROUP BY D.IDMEDICAMENTO, M.DESCRIPCIONMED
ORDER BY 2 DESC;

--B) LISTAR LOS PROVEEDORES DE MÁS DE 2 SUCURSALES. EL ESTADO DEL PROVEEDOR(EN LA SUCURSAL) DEBE SER ACTIVO

--PLANTEAMIENTO: HACER TABLA QUE MUESTRE A LOS PROVEEDORES CON MÁS DE 2 SUCURSALES(GROUP BY) Y DPS CON EL ACTIVO
SELECT * FROM EE1_PROVEEDOR; -- IDPROVEEDOR + RAZONSOCIAL
SELECT * FROM EE1_PROVEEDORXSUCURSAL; -- IDPROVEEDOR + IDSUCURSAL + ACTIVO
SELECT * FROM EE1_SUCURSAL; -- IDSUCURSAL

SELECT P.IDPROVEEDOR , P.RAZONSOCIAL , COUNT(*) AS NMRSUCURSALES
FROM EE1_PROVEEDOR P, EE1_PROVEEDORXSUCURSAL PS, EE1_SUCURSAL S
WHERE ps.idproveedor = p.idproveedor AND s.idsucursal = ps.idsucursal
AND PS.ACTIVO = 'A'
GROUP BY P.IDPROVEEDOR , P.RAZONSOCIAL 
HAVING COUNT(*)>2
ORDER BY 1;

--C) DAR BONIFICACION A LOS VENDEDORES CUYO TOTAL DE VENTAS EN EL MES DE SETIEMBRE SEA MAYOR A 1K (TODAS SUCURSALES)
-- QUE HAYA TENIDO + DE 10 VENTAS. ORDENADO POR EL MONTO TOTAL EN DESC

--PLANTEAMIENTO: CREAR TABLA QUE MUESTRA EL SUM DE (MONTO TOTAL) EN SETIEMBRE SEA MAYOR A 1K
SELECT * FROM EE1_VENDEDOR; -- IDVENDEDOR , NOMBRES||' '||APEPATERNO||' '||APEMATERNO
SELECT * FROM EE1_VENTA; -- IDVENDEDOR + IDVENTA + FECHAVENTA + MONTOTOTAL + IDSUCURSAL
--FORMA SIN SUBCONSULTA
SELECT V.IDVENDEDOR, V.NOMBRES||' '||V.APEPATERNO||' '||V.APEMATERNO AS NOMBRECOMPLETO, SUM(VT.MONTOTOTAL) AS MONTOTOTAL, COUNT(*) AS NMRVENTAS
FROM EE1_VENDEDOR V, EE1_VENTA VT
WHERE vT.idvendedor = v.idvendedor 
AND TO_CHAR(FECHAVENTA,'MM') = '09'
GROUP BY V.IDVENDEDOR, V.NOMBRES||' '||V.APEPATERNO||' '||V.APEMATERNO
HAVING SUM(VT.MONTOTOTAL)>1000 AND COUNT(*)>10
ORDER BY 3 ASC;
--FORMA CON SUBCONSULTA -> POCO EFECTIVO PQ AGARRA MÁS MEMORIA
SELECT V.IDVENDEDOR, (V.NOMBRES||' '||V.APEPATERNO||' '||V.APEMATERNO)AS NOMBRECOMPLETO, SUM (VT.MONTOTOTAL), COUNT(VT.IDVENTA)
FROM EE1_VENDEDOR V, EE1_VENTA VT
WHERE vt.idvendedor = v.idvendedor AND TO_CHAR(FECHAVENTA,'MM') = '09'
AND (SELECT SUM(V2.MONTOTOTAL) FROM EE1_VENTA V2 WHERE V.IDVENDEDOR = V2.IDVENDEDOR AND TO_CHAR(FECHAVENTA,'MM') = '09')>1000
GROUP BY V.IDVENDEDOR, (V.NOMBRES||' '||V.APEPATERNO||' '||V.APEMATERNO)
ORDER BY 3 ASC;


