--LABORATORIO 4
--2022-1 --> 
--PARTE CALIFICADA
SET SERVEROUTPUT ON;
--PREGUNTA 1:
/
SELECT * FROM CE_CLIENTE;
SELECT * FROM CE_PEDIDO;
/
SELECT COUNT(*)
FROM CE_CLIENTE C, CE_PEDIDO P
WHERE C.ID_CLIENTE = P.ID_CLIENTE
AND C.NUMERO_DOCUMENTO = '42525748'
AND P.FECHA_REGISTRO BETWEEN TO_DATE('15/03/2022','DD/MM/YYYY') AND TO_DATE('15/06/2022','DD/MM/YYYY');
/
CREATE OR REPLACE PROCEDURE XX_CANTIDAD_PEDIDOS (DOC_CLIENTE NUMBER, FECHA_IN DATE, FECHA_OUT DATE)
IS
    C_CANTIDAD NUMBER;
BEGIN
    SELECT COUNT(*)INTO C_CANTIDAD
    FROM CE_CLIENTE C, CE_PEDIDO P
    WHERE C.ID_CLIENTE = P.ID_CLIENTE
    AND C.NUMERO_DOCUMENTO = DOC_CLIENTE
    AND P.FECHA_REGISTRO BETWEEN FECHA_IN AND FECHA_OUT;
    DBMS_OUTPUT.PUT_LINE('Hay '||C_CANTIDAD||' pedidos para el cliente'||DOC_CLIENTE||' en el rango de '||TO_CHAR(FECHA_IN,'dd-MON-YY')||' al '||TO_CHAR(FECHA_OUT,'dd-MON-YY'));
END;
/
EXEC XX_CANTIDAD_PEDIDOS('42525748','15/03/2022','15/06/2022');
/
--PREGUNTA 2:
CREATE OR REPLACE PROCEDURE IMPRIMIR_ARTICULO (NOMBREPROD VARCHAR2)
IS
    --de un producto en especifico me saca la informacion a imprimir
    CURSOR PRODUCTO(C_NOMBREP VARCHAR2 )IS 
        SELECT P.RAZON_SOCIAL,P.NUMERO_TELEFONO,P.CORREO_ELECTRONICO
        FROM CE_PROVEEDOR P , CE_PRODUCTO PRO
        WHERE PRO.NOMBRE = C_NOMBREP AND PRO.ID_PROVEEDOR = P.ID_PROVEEDOR;
    DATOS_PROVEEDOR PRODUCTO%ROWTYPE;
BEGIN
    --abro el cursor
    OPEN PRODUCTO (NOMBREPROD);
    dbms_output.put_line('ARTICULO: '||NOMBREPROD);
    dbms_output.put_line('---------------------------------------------------');
    LOOP --empiezo a recorrer el cursor para que me imprima los datos que encuentre
    FETCH PRODUCTO INTO DATOS_PROVEEDOR;
    EXIT WHEN PRODUCTO%NOTFOUND;
    dbms_output.put_line('PROVEEDOR: '||DATOS_PROVEEDOR.RAZON_SOCIAL);
    dbms_output.put_line('TELEFONO: '||DATOS_PROVEEDOR.NUMERO_TELEFONO);
    dbms_output.put_line('CORREO ELECTRONICO: '||DATOS_PROVEEDOR.CORREO_ELECTRONICO);
    END LOOP;
    CLOSE PRODUCTO;
END;
/
EXEC IMPRIMIR_ARTICULO ('CELULAR GALAXY Z FOLD2');
/
--PREGUNTA 3
CREATE OR REPLACE PROCEDURE IMPRIMIR_STOCK_PRODUCTO (RUCPROV NUMBER)
IS  
    CURSOR ARTICULOS (C_RUC NUMBER) IS 
        SELECT PRO.NOMBRE, PRO.STOCK 
        FROM CE_PROVEEDOR P , CE_PRODUCTO PRO
        WHERE C_RUC = P.RUC AND P.ID_PROVEEDOR = PRO.ID_PROVEEDOR;
    DATOS_ARTICULOS ARTICULOS%ROWTYPE;
BEGIN 
    --abro el cursor e imprimo los datos unicos
    OPEN ARTICULOS (RUCPROV);
    dbms_output.put_line('PROVEEDOR: '||RUCPROV);
    dbms_output.put_line('---------------------------------------------------');
    dbms_output.put_line('ARTICULO                                          | STOCK');
    dbms_output.put_line('---------------------------------------------------');
    --empieza la iterativa porque tengo que buscar los articulos de ese producto
    LOOP
    FETCH ARTICULOS INTO DATOS_ARTICULOS;
    EXIT WHEN ARTICULOS%NOTFOUND;
    dbms_output.put_line(DATOS_ARTICULOS.NOMBRE ||' | '||DATOS_ARTICULOS.STOCK);
    END LOOP;
    CLOSE ARTICULOS;
END;
/
EXEC IMPRIMIR_STOCK_PRODUCTO (8888888888);
/
--PREGUNTAS 4
CREATE OR REPLACE PROCEDURE LISTA_PEDIDO_X_CLIENTE (TEXTO VARCHAR2)
IS
    CURSOR CLIENTES (PARAMETRO VARCHAR2) IS
        SELECT NOMBRES,APELLIDO_PATERNO,APELLIDO_MATERNO,NUMERO_DOCUMENTO,ID_CLIENTE
        FROM CE_CLIENTE
        WHERE NOMBRES LIKE '%'||PARAMETRO||'%' OR 
        APELLIDO_PATERNO LIKE '%'||PARAMETRO||'%' OR 
        APELLIDO_MATERNO LIKE '%'||PARAMETRO||'%';
    DATA_CLIENTES CLIENTES%ROWTYPE;
    --APLICARE EL CURSOR Y EL PARAMETRO SERÁ EL ID SACADO DEL ANTERIOR CURSOR
    CURSOR L_PEDIDOS (NUM_CLIENTE NUMBER) IS
        SELECT P.CODIGO,P.MONTO_TOTAL,P.FECHA_ENTREGA
        FROM CE_PEDIDO P 
        WHERE NUM_CLIENTE=P.ID_CLIENTE;
    DATA_PEDIDOS L_PEDIDOS%ROWTYPE;
BEGIN
    OPEN CLIENTES(TEXTO);
    dbms_output.put_line('PARAMETRO:'||TEXTO);
    LOOP
    FETCH CLIENTES INTO DATA_CLIENTES;
    EXIT WHEN CLIENTES%NOTFOUND;
    dbms_output.put_line('---------------------------------------------------');
    dbms_output.put_line('CLIENTE: '||DATA_CLIENTES.NOMBRES||' '||
                        DATA_CLIENTES.APELLIDO_PATERNO||' '||DATA_CLIENTES.APELLIDO_MATERNO||'('||DATA_CLIENTES.NUMERO_DOCUMENTO||')');
    dbms_output.put_line('---------------------------------------------------');
    dbms_output.put_line('CODIGO PEDIDO:         |   MONTO TOTAL   |      FECHA ENTREGA ');
        OPEN L_PEDIDOS ( DATA_CLIENTES.ID_CLIENTE);
        LOOP
        FETCH L_PEDIDOS INTO DATA_PEDIDOS;
        EXIT WHEN L_PEDIDOS%NOTFOUND;
        dbms_output.put_line(RPAD(DATA_PEDIDOS.CODIGO, 23) ||'|     '||
        RPAD(DATA_PEDIDOS.MONTO_TOTAL, 12)|| '|       '||
        RPAD(TO_CHAR(DATA_PEDIDOS.FECHA_ENTREGA, 'DD/MON/YYYY'), 10));
        END LOOP;
    CLOSE L_PEDIDOS;
    dbms_output.put_line('---------------------------------------------------');
   END LOOP;
    CLOSE CLIENTES;
END;
/
SET SERVEROUTPUT ON;
EXEC LISTA_PEDIDO_X_CLIENTE ('E');
/
--PREGUNTA 5
CREATE OR REPLACE PROCEDURE CANT_PRODUC_CLIENTE (NUM_DOC NUMBER,NAME_PROD VARCHAR2)
IS
    CANTIDAD NUMBER;
BEGIN
    SELECT COUNT(*) INTO CANTIDAD
    FROM CE_CLIENTE C,CE_PRODUCTO PROD,CE_PEDIDO PED,CE_PEDIDO_DETALLE DET
    WHERE NUM_DOC=C.NUMERO_DOCUMENTO AND NAME_PROD = PROD.NOMBRE
        AND PED.ID_CLIENTE=C.ID_CLIENTE AND PROD.ID_PRODUCTO=DET.ID_PRODUCTO
        AND PED.ID_PEDIDO=DET.ID_PEDIDO;
    dbms_output.put_line('EL CLIENTE '||NUM_DOC||' HA COMPRADO '||
            CANTIDAD||' UNIDADES DE '||NAME_PROD);
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN dbms_output.put_line('DATO MAL ESCRITO');
END;
/
EXEC CANT_PRODUC_CLIENTE('42525748','CELULAR SAMSUNG GALAXY S20');
/
--PREGUNTA 6
SELECT * FROM CE_DESCUENTO;
SELECT * FROM CE_PRODUCTO;
/
SELECT D.ID_PRODUCTO
FROM CE_PRODUCTO P, CE_DESCUENTO D
WHERE P.ID_PRODUCTO = D.ID_PRODUCTO AND P.NOMBRE = 'REFRIGERADORA LG NO FROST';
/
UPDATE CE_PRODUCTO P, CE_DESCUENTO D
SET FECHA_FIN = SYSDATE-1
WHERE D.PORCENTAJE = 0.25 
AND P.ID_PRODUCTO = D.ID_PRODUCTO AND P.NOMBRE = 'REFRIGERADORA LG NO FROST';
/
INSERT INTO CE_DESCUENTO VALUES(ID_DESCUENTO+1,C_ID_PRODUCTO,NUEVO_DESCUENTO,SYSDATE,LAST_DAY(TRUNC(SYSDATE, 'YYYY'));
/
CREATE SEQUENCE SEQ_ID
START WITH 6
MINVALUE 3
MAXVALUE 20;
/
CREATE OR REPLACE PROCEDURE REGISTRAR_DESCUENTO(NOMBRE_PRODUCTO VARCHAR2, NUEVO_DESCUENTO NUMBER)
IS
    C_ID_PRODUCTO NUMBER;
BEGIN
    SELECT D.ID_PRODUCTO INTO C_ID_PRODUCTO
    FROM CE_PRODUCTO P, CE_DESCUENTO D
    WHERE P.ID_PRODUCTO = D.ID_PRODUCTO AND P.NOMBRE = NOMBRE_PRODUCTO;
    
    --PARA LA ACTUALIACION
    UPDATE CE_DESCUENTO D
    SET D.FECHA_FIN = SYSDATE-1 
    WHERE D.ID_PRODUCTO = C_ID_PRODUCTO;
    
    --AHORA INSERTO LO NUEVO QUE ME PIDEN
    INSERT INTO CE_DESCUENTO VALUES(SEQ_ID.NEXTVAL,C_ID_PRODUCTO,NUEVO_DESCUENTO,SYSDATE,LAST_DAY(TRUNC(SYSDATE, 'YYYY')));
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        dbms_output.put_line('El articulo '||NOMBRE_PRODUCTO||' no se encuentra registrado');
END;
/
EXEC REGISTRAR_DESCUENTO('REFRIGERADORA LG NO FROST',070);
/
--PREGUNTA 7:
SELECT * FROM CE_PRODUCTO;
SELECT * FROM CE_MARCA_PRODUCTO;
/
SELECT COUNT(*) , P.NOMBRE
FROM CE_PRODUCTO C, CE_MARCA_PRODUCTO P, CE_PEDIDO PE, CE_PEDIDO_DETALLE PD
WHERE C.ID_MARCA = P.ID_MARCA
AND PD.ID_PRODUCTO = C.ID_PRODUCTO AND PE.ID_PEDIDO = PD.ID_PEDIDO
AND PE.FECHA_REGISTRO BETWEEN TO_DATE('01/01/2022','DD/MM/YYYY') AND TO_DATE('31/10/2022','DD/MM/YYYY')
GROUP BY P.NOMBRE;
/
CREATE OR REPLACE PROCEDURE XX_CANTIDAD_UNIDADES_VENTIDADAS (FECHA_IN DATE, FECHA_OUT DATE)
IS
    C_CANTIDAD NUMBER;
    C_NOMBRE VARCHAR2(20);
BEGIN
    SELECT COUNT(*) , P.NOMBRE INTO C_CANTIDAD, C_NOMBRE
    FROM CE_PRODUCTO C, CE_MARCA_PRODUCTO P, CE_PEDIDO PE, CE_PEDIDO_DETALLE PD
    WHERE C.ID_MARCA = P.ID_MARCA
    AND PD.ID_PRODUCTO = C.ID_PRODUCTO AND PE.ID_PEDIDO = PD.ID_PEDIDO
    AND PE.FECHA_REGISTRO BETWEEN FECHA_IN AND FECHA_OUT
    GROUP BY P.NOMBRE;
    DBMS_OUTPUT.PUT_LINE('La marca con más unidades vendidas entre '||TO_CHAR(FECHA_IN,'dd-MON-YY')||' y '||TO_CHAR(FECHA_OUT,'dd-MON-YY')||' es '||C_NOMBRE);
END;
/
EXEC XX_CANTIDAD_UNIDADES_VENTIDADAS ('01/01/2022','31/10/2022');
--
--TERMINADO :)