DROP TABLE E1_INSPECTOR CASCADE CONSTRAINTS;
DROP TABLE E1_PERSONAL CASCADE CONSTRAINTS;
DROP TABLE E1_ADMINTELEFONO;
DROP TABLE E1_EDIFICIO CASCADE CONSTRAINTS;
DROP TABLE E1_ADMINISTRADOR;
DROP TABLE E1_CLIENTECORP CASCADE CONSTRAINTS;
DROP TABLE E1_LIMPIEZA;
DROP TABLE E1_APARTAMENTO;
DROP TABLE E1_INSPECCIONA;