
DROP TABLE E2ORDENEXAMEN CASCADE CONSTRAINTS;

CREATE TABLE E2ORDENEXAMEN (
       ORDENEXAMEN          NUMBER(6) NOT NULL,
       TIPO_EXAMEN          CHAR(2) NOT NULL,
       MEDICO               CHAR(8) NOT NULL,
       ESPECIALIDAD         CHAR(2) NOT NULL,
       CICLOATENCION        NUMBER NOT NULL,
       FECHADATENCION       DATE NOT NULL,
       HORAINICIO           CHAR(4) NOT NULL,
       FECHAEXAMEN          DATE NULL
);


ALTER TABLE E2ORDENEXAMEN
       ADD  ( CONSTRAINT XPKE2ORDENEXAMEN PRIMARY KEY (ORDENEXAMEN) ) ;


DROP TABLE E2TIPOEXAMEN CASCADE CONSTRAINTS;

CREATE TABLE E2TIPOEXAMEN (
       TIPO_EXAMEN          CHAR(2) NOT NULL,
       DESCRIPCION          VARCHAR2(100) NOT NULL,
       COSTO                NUMBER(6,2) NULL
);


ALTER TABLE E2TIPOEXAMEN
       ADD  ( CONSTRAINT XPKE2TIPOEXAMEN PRIMARY KEY (TIPO_EXAMEN) ) ;


DROP TABLE E2DIADATENCION CASCADE CONSTRAINTS;

CREATE TABLE E2DIADATENCION (
       CICLOATENCION        NUMBER NOT NULL,
       MEDICO               CHAR(8) NOT NULL,
       ESPECIALIDAD         CHAR(2) NOT NULL,
       DIA                  CHAR(1) NOT NULL,
       HORAINICIO           CHAR(4) NOT NULL,
       HORAFIN              CHAR(4) NOT NULL
);


ALTER TABLE E2DIADATENCION
       ADD  ( CONSTRAINT XPKE2DIADATENCION PRIMARY KEY (MEDICO, 
              ESPECIALIDAD, CICLOATENCION, DIA) ) ;


DROP TABLE E2DIA CASCADE CONSTRAINTS;

CREATE TABLE E2DIA (
       DIA                  CHAR(1) NOT NULL,
       DESCRIPCION          CHAR(100) NULL
);


ALTER TABLE E2DIA
       ADD  ( CONSTRAINT XPKE2DIA PRIMARY KEY (DIA) ) ;


DROP TABLE E2PERSONA CASCADE CONSTRAINTS;

CREATE TABLE E2PERSONA (
       CODIGO               CHAR(8) NOT NULL,
       NOMBRES              VARCHAR2(50) NULL,
       APEPATERNO           VARCHAR2(100) NULL,
       APEMATERNO           VARCHAR2(100) NULL
);


ALTER TABLE E2PERSONA
       ADD  ( CONSTRAINT XPKE2PERSONA PRIMARY KEY (CODIGO) ) ;


DROP TABLE E2CITA CASCADE CONSTRAINTS;

CREATE TABLE E2CITA (
       MEDICO               CHAR(8) NOT NULL,
       ESPECIALIDAD         CHAR(2) NOT NULL,
       CICLOATENCION        NUMBER NOT NULL,
       FECHADATENCION       DATE NOT NULL,
       HORAINICIO           CHAR(4) NOT NULL,
       HORAFIN              CHAR(4) NOT NULL,
       ASOCIADO             CHAR(8) NOT NULL,
       INDICAASISTENCIA     CHAR(1) NOT NULL,
       DIAGNOSTICO          VARCHAR2(1500) NULL,
       OBSERVACIONES        VARCHAR2(1500) NULL,
       INDICAREPROG		CHAR(1) NOT NULL,
       COSTOCONSULTA		NUMBER NULL,
       COSTOEXAMENES		NUMBER NULL
);


ALTER TABLE E2CITA
       ADD  ( CONSTRAINT XPKE2CITA PRIMARY KEY (MEDICO, ESPECIALIDAD, 
              CICLOATENCION, FECHADATENCION, HORAINICIO) ) ;


DROP TABLE E2FECHADATENCION CASCADE CONSTRAINTS;

CREATE TABLE E2FECHADATENCION (
       MEDICO               CHAR(8) NOT NULL,
       ESPECIALIDAD         CHAR(2) NOT NULL,
       CICLOATENCION        NUMBER NOT NULL,
       FECHADATENCION       DATE NOT NULL,
       INDICACANCELADO      CHAR(1) NOT NULL
);


ALTER TABLE E2FECHADATENCION
       ADD  ( CONSTRAINT XPKE2FECHADATENCION PRIMARY KEY (MEDICO, 
              ESPECIALIDAD, CICLOATENCION, FECHADATENCION) ) ;


DROP TABLE E2CICLODATENCION CASCADE CONSTRAINTS;

CREATE TABLE E2CICLODATENCION (
       MEDICO               CHAR(8) NOT NULL,
       ESPECIALIDAD         CHAR(2) NOT NULL,
       CICLOATENCION        NUMBER NOT NULL,
       FECHAINICIO          DATE NOT NULL,
       FECHAFIN             DATE NOT NULL
);


ALTER TABLE E2CICLODATENCION
       ADD  ( CONSTRAINT XPKE2CICLODATENCION PRIMARY KEY (MEDICO, 
              ESPECIALIDAD, CICLOATENCION) ) ;


DROP TABLE E2MEDICOXESPECIALIDAD CASCADE CONSTRAINTS;

CREATE TABLE E2MEDICOXESPECIALIDAD (
       ESPECIALIDAD         CHAR(2) NOT NULL,
       MEDICO               CHAR(8) NOT NULL,
       CONSULTORIO          CHAR(2) NULL,
       COSTOCONSULTA	    NUMBER(5,2) NULL
);


ALTER TABLE E2MEDICOXESPECIALIDAD
       ADD  ( CONSTRAINT XPKE2MEDICOXESPECIALIDAD PRIMARY KEY (MEDICO, 
              ESPECIALIDAD) ) ;


DROP TABLE E2CONSULTORIO CASCADE CONSTRAINTS;

CREATE TABLE E2CONSULTORIO (
       CONSULTORIO          CHAR(2) NOT NULL,
       DESCRIPCION          CHAR(4) NULL
);


ALTER TABLE E2CONSULTORIO
       ADD  ( CONSTRAINT XPKE2CONSULTORIO PRIMARY KEY (CONSULTORIO) ) ;


DROP TABLE E2ASOCIADO CASCADE CONSTRAINTS;

CREATE TABLE E2ASOCIADO (
       ASOCIADO             CHAR(8) NOT NULL,
       FECHAASOCIADO        DATE NOT NULL
);


ALTER TABLE E2ASOCIADO
       ADD  ( CONSTRAINT XPKE2ASOCIADO PRIMARY KEY (ASOCIADO) ) ;


DROP TABLE E2ESPECIALIDAD CASCADE CONSTRAINTS;

CREATE TABLE E2ESPECIALIDAD (
       ESPECIALIDAD         CHAR(2) NOT NULL,
       NOMBRE               VARCHAR2(50) NULL,
       DESCRIPCION          VARCHAR2(100) NULL
);


ALTER TABLE E2ESPECIALIDAD
       ADD  ( CONSTRAINT XPKE2ESPECIALIDAD PRIMARY KEY (ESPECIALIDAD) ) ;


DROP TABLE E2MEDICO CASCADE CONSTRAINTS;

CREATE TABLE E2MEDICO (
       MEDICO               CHAR(8) NOT NULL,
       NUMCOLMEDICO         CHAR(10) NOT NULL
);


ALTER TABLE E2MEDICO
       ADD  ( CONSTRAINT E2XPKE2MEDICO PRIMARY KEY (MEDICO) ) ;


ALTER TABLE E2ORDENEXAMEN
       ADD  ( CONSTRAINT E2XFK_TIPOEXAMEN_ORDENEXAMEN
              FOREIGN KEY (TIPO_EXAMEN)
                             REFERENCES E2TIPOEXAMEN ) ;


ALTER TABLE E2ORDENEXAMEN
       ADD  ( CONSTRAINT E2XFK_CITA_ORDENEXAMEN
              FOREIGN KEY (MEDICO, ESPECIALIDAD, CICLOATENCION, 
              FECHADATENCION, HORAINICIO)
                             REFERENCES E2CITA ) ;


ALTER TABLE E2DIADATENCION
       ADD  ( CONSTRAINT E2XFK_DIA_DIADATEN
              FOREIGN KEY (DIA)
                             REFERENCES E2DIA ) ;


ALTER TABLE E2DIADATENCION
       ADD  ( CONSTRAINT E2XFK_CICLOATEN_DIADATEN
              FOREIGN KEY (MEDICO, ESPECIALIDAD, CICLOATENCION)
                             REFERENCES E2CICLODATENCION ) ;


ALTER TABLE E2CITA
       ADD  ( CONSTRAINT E2XFK_FECHAATEN_CITA
              FOREIGN KEY (MEDICO, ESPECIALIDAD, CICLOATENCION, 
              FECHADATENCION)
                             REFERENCES E2FECHADATENCION ) ;


ALTER TABLE E2CITA
       ADD  ( CONSTRAINT E2XFK_ASOCIADO_CITA
              FOREIGN KEY (ASOCIADO)
                             REFERENCES E2ASOCIADO ) ;


ALTER TABLE E2FECHADATENCION
       ADD  ( CONSTRAINT E2XFK_CICLOATEN_FECHAATEN
              FOREIGN KEY (MEDICO, ESPECIALIDAD, CICLOATENCION)
                             REFERENCES E2CICLODATENCION ) ;


ALTER TABLE E2CICLODATENCION
       ADD  ( CONSTRAINT E2XFK_MEDXESPECI_CICLOATENCION
              FOREIGN KEY (MEDICO, ESPECIALIDAD)
                             REFERENCES E2MEDICOXESPECIALIDAD ) ;


ALTER TABLE E2MEDICOXESPECIALIDAD
       ADD  ( CONSTRAINT E2XFK_MEDICO_MEDIXESPE
              FOREIGN KEY (MEDICO)
                             REFERENCES E2MEDICO ) ;


ALTER TABLE E2MEDICOXESPECIALIDAD
       ADD  ( CONSTRAINT E2XFK_ESPECIALIDAD_MEDICOXES
              FOREIGN KEY (ESPECIALIDAD)
                             REFERENCES E2ESPECIALIDAD ) ;


ALTER TABLE E2MEDICOXESPECIALIDAD
       ADD  ( CONSTRAINT E2XFK_CONSULTORIO_MEDXESPECI
              FOREIGN KEY (CONSULTORIO)
                             REFERENCES E2CONSULTORIO ) ;


ALTER TABLE E2ASOCIADO
       ADD  ( CONSTRAINT E2XFK_PERSONA_ASOCIADO
              FOREIGN KEY (ASOCIADO)
                             REFERENCES E2PERSONA
                             ON DELETE CASCADE ) ;


ALTER TABLE E2MEDICO
       ADD  ( CONSTRAINT E2XFK_PERSONA_MEDICO
              FOREIGN KEY (MEDICO)
                             REFERENCES E2PERSONA
                             ON DELETE CASCADE ) ;

