/* tabla Pais */
CREATE TABLE PAIS (
   COD_PAIS VARCHAR2(2) NOT NULL,
   DESCRIPCION VARCHAR2(100),
  CONSTRAINT PK_PAIS PRIMARY KEY (COD_PAIS)
);

/* tabla PERSONA */
CREATE TABLE PERSONA (
	DNI NUMBER(8) NOT NULL,
	NOMBRES VARCHAR2(40) NOT NULL,
	APELLIDO1 VARCHAR2(15) NOT NULL,
	APELLIDO2 VARCHAR2(15),
	NACIONALIDAD VARCHAR2(2),
	DIRECCION VARCHAR2(50),
	SEXO CHAR(1),
	FECHA_NAC DATE,
	EMAIL VARCHAR2(25),
  CONSTRAINT PK_PERSONA PRIMARY KEY ( DNI ),
  CONSTRAINT FK_NACIONALIDAD FOREIGN KEY (NACIONALIDAD) REFERENCES PAIS (COD_PAIS)
  
);

/* tabla departamentos */
CREATE TABLE DEPARTAMENTOS (
	COD_DPTO VARCHAR2(5) NOT NULL,
	NOMBRE_DPTO VARCHAR2(30) NOT NULL,
	RESPONSABLE NUMBER(8),
	NRO_PABELLONES NUMBER(2),
	NRO_CAFETERIAS NUMBER(2),
  CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY (COD_DPTO),
  CONSTRAINT FK_RESPONSABLE FOREIGN KEY (RESPONSABLE) REFERENCES PERSONA (DNI)

);

/* tabla BIBLIOTECA */
CREATE TABLE BIBLIOTECA (
	COD_BIBLIO VARCHAR2(5) NOT NULL,
	NOMBRE_BIBLIO VARCHAR2(40) NOT NULL,
	UBICACION VARCHAR2(30),
	CANT_SALAS NUMBER(4),
	CANT_ESTANTES NUMBER(4),
  CONSTRAINT PK_BIBLIOTECA PRIMARY KEY ( COD_BIBLIO )
);

/* tabla LIBRO */
CREATE TABLE TIPOLIBRO (
   COD_TIPO_LIBRO VARCHAR2(5) NOT NULL,
   DESCRIPCION VARCHAR2(100),
  CONSTRAINT PK_TIPOLIBRO PRIMARY KEY (COD_TIPO_LIBRO)
);

/* tabla LIBRO */
CREATE TABLE LIBRO (
   COD_LIBRO VARCHAR2(5) NOT NULL,
   TITULO VARCHAR2(100),
   AUTOR VARCHAR2(100),
   EDITORAL VARCHAR2(50),
   ANHO_PUBLICA NUMBER(4),
   TIPO_LIBRO VARCHAR2(5),
  CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO),
  CONSTRAINT FK_TIPO_LIBRO FOREIGN KEY (TIPO_LIBRO) REFERENCES TIPOLIBRO (COD_TIPO_LIBRO)
);

/* tabla ALUMNO */
CREATE TABLE ALUMNO(
	COD_ALUMNO NUMBER(8) NOT NULL,
	FACULTAD VARCHAR2(5) NOT NULL,
	ESPECIALIDAD VARCHAR2(100) NOT NULL,
	NIVEL_ESTUDIO NUMBER(2) NOT NULL,
  CONSTRAINT PK_ALUMNO PRIMARY KEY ( COD_ALUMNO ),
  CONSTRAINT FK_ALUMNO FOREIGN KEY (COD_ALUMNO) REFERENCES PERSONA (DNI)
);

CREATE TABLE LIBRO_BIBLIOTECA(
  COD_BIBLIO VARCHAR2(5) NOT NULL,
  COD_LIBRO VARCHAR2(5) NOT NULL,
  TOTAL_EJEMPLAR NUMBER(3) NOT NULL,
  ESTANTE VARCHAR2(5),
  CONSTRAINT PK_LIB_BIBL PRIMARY KEY (COD_BIBLIO, COD_LIBRO),
  CONSTRAINT FK_COD_BIBLIO FOREIGN KEY (COD_BIBLIO) REFERENCES BIBLIOTECA (COD_BIBLIO),
  CONSTRAINT FK_LIBRO_BIB FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO (COD_LIBRO)
);

CREATE TABLE LIBRO_PRESTADO(
  COD_BIBLIO VARCHAR2(5) NOT NULL,
  COD_LIBRO VARCHAR2(5) NOT NULL,
  COD_ALUMNO NUMBER(8) NOT NULL,
  FECHA_SOLICITUD DATE NOT NULL,
  FECHA_ENTREGA DATE,
  NRO_DIAS_PRESTADO NUMBER(2),
  CONSTRAINT PK_LIB_PRES PRIMARY KEY (COD_BIBLIO, COD_LIBRO, COD_ALUMNO),
  CONSTRAINT FK_CODPRES_BIBLIO FOREIGN KEY (COD_BIBLIO, COD_LIBRO) REFERENCES LIBRO_BIBLIOTECA (COD_BIBLIO, COD_LIBRO),
  CONSTRAINT FK_ALUMNOPRES FOREIGN KEY (COD_ALUMNO) REFERENCES PERSONA (DNI)
);