BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE SPB_PAIS CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE SPB_PERSONA CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE SPB_DEPARTAMENTO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE SPB_BIBLIOTECA CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE SPB_TIPO_LIBRO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE SPB_LIBRO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE SPB_ALUMNO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE SPB_LIBRO_BIBLIOTECA CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE SPB_LIBRO_PRESTADO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE PERSONA CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE PAIS CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE BIBLIOTECA CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE TIPOLIBRO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE LIBRO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE ALUMNO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE LIBRO_BIBLIOTECA CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE LIBRO_PRESTADO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE CE_CLASE CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE CE_HORARIO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE CE_HORARIO_ALUMNO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE CE_PERSOMA CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
	EXECUTE IMMEDIATE 'DROP TABLE CE_UBIGEO CASCADE CONSTRAINTS';
	EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/
