CREATE TABLE SPB_PAIS (
   COD_PAIS VARCHAR2(4 BYTE) NOT NULL,
   DESCRIPCION VARCHAR2(100 BYTE),
   CONSTRAINT PK_PAIS PRIMARY KEY (COD_PAIS)
);

CREATE TABLE SPB_PERSONA (
   DNI NUMBER NOT NULL,
   NOMBRES VARCHAR2(40 BYTE) NOT NULL,
   APELLIDO1 VARCHAR2(15 BYTE) NOT NULL,
   APELLIDO2 VARCHAR2(15 BYTE),
   NACIONALIDAD VARCHAR2(4 BYTE),
   DIRECCION VARCHAR2(50 BYTE),
   SEXO CHAR(1 BYTE),
   FECHA_NAC DATE,
   EMAIL VARCHAR2(25 BYTE),
   CONSTRAINT PK_PERSONA PRIMARY KEY ( DNI ),
   CONSTRAINT FK_NACIONALIDAD FOREIGN KEY (NACIONALIDAD) REFERENCES SPB_PAIS (COD_PAIS)
);

CREATE TABLE SPB_DEPARTAMENTO (
   COD_DPTO VARCHAR2(5 BYTE) NOT NULL,
   NOMBRE_DPTO VARCHAR2(30 BYTE) NOT NULL,
   RESPONSABLE NUMBER,
   NRO_PABELLONES NUMBER,
   NRO_CAFETERIAS NUMBER,
   CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DPTO),
   CONSTRAINT FK_RESPONSABLE FOREIGN KEY (RESPONSABLE) REFERENCES SPB_PERSONA (DNI)
);

CREATE TABLE SPB_BIBLIOTECA (
   COD_BIBLIO VARCHAR2(5 BYTE) NOT NULL,
   NOMBRE_BIBLIO VARCHAR2(40 BYTE) NOT NULL,
   UBICACION VARCHAR2(30 BYTE),
   CANT_SALAS NUMBER,
   CANT_ESTANTES NUMBER,
   CONSTRAINT PK_BIBLIOTECA PRIMARY KEY ( COD_BIBLIO )
);

CREATE TABLE SPB_TIPO_LIBRO (
   COD_TIPO_LIBRO VARCHAR2(5 BYTE) NOT NULL,
   DESCRIPCION VARCHAR2(100 BYTE),
   CONSTRAINT PK_TIPOLIBRO PRIMARY KEY (COD_TIPO_LIBRO)
);

CREATE TABLE SPB_LIBRO (
   COD_LIBRO VARCHAR2(5 BYTE) NOT NULL,
   TITULO VARCHAR2(100 BYTE),
   AUTOR VARCHAR2(100 BYTE),
   EDITORAL VARCHAR2(50 BYTE),
   ANHO_PUBLICA NUMBER,
   TIPO_LIBRO VARCHAR2(5 BYTE),
   CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO),
   CONSTRAINT FK_TIPO_LIBRO FOREIGN KEY (TIPO_LIBRO) REFERENCES SPB_TIPO_LIBRO (COD_TIPO_LIBRO)
);

CREATE TABLE SPB_ALUMNO (
   COD_ALUMNO NUMBER NOT NULL,
   FACULTAD VARCHAR2(5 BYTE) NOT NULL,
   ESPECIALIDAD VARCHAR2(100 BYTE) NOT NULL,
   NIVEL_ESTUDIO NUMBER NOT NULL,
   CONSTRAINT PK_ALUMNO PRIMARY KEY ( COD_ALUMNO ),
   CONSTRAINT FK_ALUMNO FOREIGN KEY (COD_ALUMNO) REFERENCES SPB_PERSONA (DNI)
);

CREATE TABLE SPB_LIBRO_BIBLIOTECA (
   COD_BIBLIO VARCHAR2(5 BYTE) NOT NULL,
   COD_LIBRO VARCHAR2(5 BYTE) NOT NULL,
   TOTAL_EJEMPLAR NUMBER NOT NULL,
   ESTANTE VARCHAR2(5 BYTE),
   CONSTRAINT PK_LIB_BIBL PRIMARY KEY (COD_BIBLIO, COD_LIBRO),
   CONSTRAINT FK_COD_BIBLIO FOREIGN KEY (COD_BIBLIO) REFERENCES SPB_BIBLIOTECA (COD_BIBLIO),
   CONSTRAINT FK_LIBRO_BIB FOREIGN KEY (COD_LIBRO) REFERENCES SPB_LIBRO (COD_LIBRO)
);

CREATE TABLE SPB_LIBRO_PRESTADO (
   COD_BIBLIO VARCHAR2(5 BYTE) NOT NULL,
   COD_LIBRO VARCHAR2(5 BYTE) NOT NULL,
   COD_ALUMNO NUMBER NOT NULL,
   FECHA_SOLICITUD DATE NOT NULL,
   FECHA_ENTREGA DATE,
   NRO_DIAS_PRESTADO NUMBER,
   CONSTRAINT PK_LIB_PRES PRIMARY KEY (COD_BIBLIO, COD_LIBRO, COD_ALUMNO),
   CONSTRAINT FK_CODPRES_BIBLIO FOREIGN KEY (COD_BIBLIO, COD_LIBRO) REFERENCES SPB_LIBRO_BIBLIOTECA (COD_BIBLIO, COD_LIBRO),
   CONSTRAINT FK_ALUMNOPRES FOREIGN KEY (COD_ALUMNO) REFERENCES SPB_PERSONA (DNI)
);