--LAB 2022-1 CALIFICADA

--PREGUNTA 1: MOSTRAR LOS PROD CON DESCUENTOS VIGENTES ORDENADOS DE MANERA DESC RESPECTO AL VALOR DEL DESCUENTO
SELECT * FROM CE_PRODUCTO; --NOMBRE PROD --ID_PROV
SELECT * FROM CE_PROVEEDOR; --NOMBRE PROV + ID
SELECT * FROM CE_DESCUENTO; --PORCENTAJE

SELECT P.NOMBRE, PV.RAZON_SOCIAL, D.PORCENTAJE
FROM CE_PRODUCTO P, CE_PROVEEDOR PV, CE_DESCUENTO D
WHERE p.id_producto = d.id_producto
AND pv.id_proveedor = p.id_proveedor
--En esta consulta, la cadena '12/04/2022' se convierte en una fecha utilizando la función TO_DATE()
--que toma dos argumentos: la cadena a convertir y el formato en el que se encuentra la cadena.
AND TRUNC(TO_DATE('12/04/2022', 'DD/MM/YYYY')) BETWEEN D.FECHA_INICIO AND D.FECHA_FIN
ORDER BY D.PORCENTAJE DESC;

--PREGUNTA 2: MOSTRAR EL MONTO PROM DE LOS PEDIDOS QUE FUERON PAGADOS CON EL MEDIO VISA
SELECT * FROM CE_PEDIDO; --MONTO_TOTAL + ID_MEDIO_PAGO
SELECT * FROM CE_MEDIO_PAGO; --NOMBRE

SELECT AVG(MONTO_TOTAL) AS MONTO_PROMEDIO
FROM CE_PEDIDO P, CE_MEDIO_PAGO M
WHERE p.id_medio_pago = m.id_medio_pago
AND M.NOMBRE = 'VISA';

--PREGUNTA 3: MOSTRAR NOMBRE Y APELLIDO CONCATENADOS DE LOS CLIENTES PER(DNI), CUYOS PED FUERON ENTR EN 2021 (AÑO PASAO)
SELECT * FROM CE_CLIENTE;--APELLIDO_PATERNO+APELLIDO_MATERNO+NOMBRES Y ID_TIPO_DOCUMENTO
SELECT * FROM CE_TIPO_DOCUMENTO;--NOMBRE + ID_TIPO_DOCUMENTO
SELECT * FROM CE_PEDIDO;--FECHA_ENTREGA

SELECT C.APELLIDO_PATERNO||' '||C.APELLIDO_MATERNO||', '||C.NOMBRES AS CLIENTE
FROM CE_CLIENTE C, CE_TIPO_DOCUMENTO T,CE_PEDIDO P
WHERE t.id_tipo_documento = c.id_tipo_documento
AND p.id_cliente = c.id_cliente
AND T.NOMBRE = 'DNI'
AND TO_CHAR(P.FECHA_ENTREGA,'YY')='21';

--PREGUNTA 4: EL PROVEEDOR "SANSUNG SAC" DESEA CONOCER LA FECHA DE CUM DE LOS CLIENTES QUE HAN CONSUMIDO SUS PROD
SELECT * FROM CE_CLIENTE; --FEHCA_NACIMIENTO + NOMBRES
SELECT * FROM CE_PEDIDO;
SELECT * FROM CE_PEDIDO_DETALLE;
SELECT * FROM CE_PRODUCTO;
SELECT * FROM CE_PROVEEDOR; --RAZON_SOCIAL;

SELECT C.APELLIDO_PATERNO, C.FECHA_NACIMIENTO
FROM CE_CLIENTE C, CE_PEDIDO P, CE_PEDIDO_DETALLE PD, CE_PROVEEDOR PV
WHERE p.id_cliente = c.id_cliente
AND pd.id_pedido = p.id_pedido
AND pd.id_pedido = p.id_pedido
AND PV.RAZON_SOCIAL = 'SANSUNG SAC';

--PREGUNTA 5: ELIMINAR A LOS CLIENTES QUE NO HAN REALIZADO NINGUN PEDIDO
SELECT * FROM CE_CLIENTE;
SELECT * FROM CE_PEDIDO;
SELECT * FROM CE_DIRECCION;

--PRIMERO OBTENEMOS LOS CLIENTES QUE SI REALIZARON ALGUN PEDIDO
SELECT C.ID_CLIENTE
FROM CE_CLIENTE C, CE_PEDIDO P
WHERE p.id_cliente = c.id_cliente;

--FIRST STEP:
--QUITAMOS LOS CLIENTES DE LA TABLA DIRECCION PORQUE EL PK ID_CLIENTE DE CE_CLIENTE ES FK DE LA TABLA CE_DIRECCION
DELETE 
FROM CE_DIRECCION D
WHERE D.ID_CLIENTE NOT IN (SELECT C.ID_CLIENTE
                           FROM CE_CLIENTE C, CE_PEDIDO P
                           WHERE p.id_cliente = c.id_cliente);

--SECOND STEP:
--AHORA QUE YA LOS QUITAMOS DE LA TABLA DIRECCION, FALTA QUITARLOS DE LA TABLA CLIENTE
DELETE
FROM CE_CLIENTE C
WHERE C.ID_CLIENTE NOT IN(SELECT C.ID_CLIENTE
                          FROM CE_CLIENTE C, CE_PEDIDO P
                          WHERE p.id_cliente = c.id_cliente);
--VERIFICO QUE SI ESTAN ELIMINADOS
SELECT * FROM CE_CLIENTE;

--PREGUNTA 6: MOSTRAR LOS TELEVISORES CON SUS RESPECTIVOS PROVEEDORES Y PRECIOS, ORDENAR DESC POR PRECIO
SELECT A.NOMBRE, A.PRECIO ,B.RAZON_SOCIAL
FROM CE_PRODUCTO A, CE_PROVEEDOR B, CE_CATEGORIA_PRODUCTO C
WHERE A.ID_PROVEEDOR = B.ID_PROVEEDOR AND A.ID_CATEGORIA=C.ID_CATEGORIA
AND C.NOMBRE = 'TELEVISORES'
ORDER BY 2 DESC;

--PREGUNTA 7:
--CON ESTO VAMOS A SELECCIONAR LOS ID DE TODOS LOS PRODUCTO QUE SEAN CELULARES Y DE LA MARCA MOTOROLLA
SELECT A.ID_PRODUCTO 
FROM CE_PRODUCTO A, CE_MARCA_PRODUCTO B, CE_CATEGORIA_PRODUCTO C
WHERE A.ID_CATEGORIA=C.ID_CATEGORIA AND A.ID_MARCA=B.ID_MARCA
AND B.NOMBRE='MOTOROLLA' AND C.NOMBRE='CELULARES';
--AHORA VAMOS A ACTUALIZAR EL STOCK DE LOS CELULARES DE MARCA MOTOROLLA EN 5 UNIDADES
UPDATE CE_PRODUCTO Z
SET Z.STOCK = Z.STOCK + 5
WHERE Z.ID_PRODUCTO IN (SELECT A.ID_PRODUCTO 
                        FROM CE_PRODUCTO A, CE_MARCA_PRODUCTO B, CE_CATEGORIA_PRODUCTO C
                        WHERE A.ID_CATEGORIA=C.ID_CATEGORIA AND A.ID_MARCA=B.ID_MARCA
                        AND B.NOMBRE='MOTOROLLA' AND C.NOMBRE='CELULARES');

--PREGUNTA 8:
SELECT *
FROM(SELECT B.PAIS_ORIGEN
    FROM CE_PRODUCTO A, CE_MARCA_PRODUCTO B
    WHERE A.ID_MARCA=B.ID_MARCA
    ORDER BY A.PRECIO ASC)
WHERE ROWNUM=1;--ESTA LINEA INDICA QUE VAMOS A TOMAR A LA FILA 1

