--LAB3 CALIFICADA 2021-1

--PREGUNTA 1: ELABORAR UN LISTADO DE LAS PROVINCIAS QUE TENGAN POR LO MENOS 12 DISTRITOS
--ORDENADA POR CANTIDAD DE DISTRITOS DE MAYOR A MENOR Y ALFABETICAMENTE POR EL NOMBRE DE LA PROVINCIA
SELECT * FROM GE_PROVINCIA;--NOMBRE
SELECT * FROM GE_DISTRITO;--DISTRITO

SELECT P.NOMBRE, COUNT(*) AS CANTIDAD_DISTRITOS
FROM GE_PROVINCIA P, GE_DISTRITO D
WHERE p.id_provincia = d.id_provincia
GROUP BY P.NOMBRE
--ME PIDEN QUE TENGAN POR LO MENOS 12 DISTRITOS
HAVING COUNT(*)>=12
ORDER BY 2 DESC, 1 ASC;

--PREGUNTA 2: LISTADO DE EVENTOS REGISTRADOS QUE TUVIERON ALGUN ASISTENTE
--PARA CADA EVENTO SE REQUIERE LA CANT DE ARCHIVOS ADJUNTOS, EL PROM DE TAMAÑO DE ESTOS EN KILOBYTES
--Y EL TAMAÑO DEL ARCHIVO MAS GRANDE CORRESPONDIENTE A ESE EVENTO
--ORDENADA DESC POR LA CANTIDAD DE ARCHIVOS ASOCIADOS, Y PROM DE TAMAÑO DE LOS ARCHIVOS
SELECT * FROM GE_EVENTO; -- NOMBRE
SELECT * FROM GE_PERSONA;
SELECT * FROM GE_PERSONA_EVENTO;--ASISTENCIA
SELECT * FROM GE_ARCHIVO;--TAMAÑO

SELECT E.NOMBRE, COUNT(*) AS CANTIDAD, TRUNC(AVG(A.TAMANO)/1024,2) AS PROMEDIO_KB, TRUNC(MAX(A.TAMANO)/1024,2)
FROM GE_EVENTO E, GE_ARCHIVO A
WHERE e.id_evento = a.id_evento
--Devolver los eventos en los que al menos una persona haya asistido
AND EXISTS (SELECT *
            FROM GE_PERSONA P, GE_PERSONA_EVENTO PV
            WHERE  pv.id_persona = p.id_persona
            AND PV.ASISTENCIA = 'A')
GROUP BY E.NOMBRE
ORDER BY 2 DESC, 3 DESC;

--OBTENER ARCHIVOS ADJUNTOS
SELECT *
FROM GE_PERSONA P, GE_PERSONA_EVENTO PV
WHERE  pv.id_persona = p.id_persona
AND PV.ASISTENCIA = 'A';

--PREGUNTA 3: LISTADO QUE TENGAN EL MISMO NOMBRE QUE LOS RESPONSABLES CON CARGO "DIRECTOR"
--NUM DOC, APELLIDOS + NOMBRES, NOMBRE EVENTO, ASISTENCIA
SELECT * FROM GE_EVENTO; -- NOMBRE
SELECT * FROM GE_PERSONA;--NOMBRE + APELLIDOS Y NMR_DOCUMENTO
SELECT * FROM GE_PERSONA_EVENTO;--ASISTENCIA

SELECT P.NRO_DOCUMENTO, P.APELLIDOS||' , '||P.NOMBRES, E.NOMBRE, PE.ASISTENCIA
FROM GE_EVENTO E, GE_PERSONA P, GE_PERSONA_EVENTO PE
WHERE pe.id_persona = p.id_persona AND pe.id_evento = e.id_evento
AND P.NOMBRES IN (SELECT P.NOMBRES
                  FROM GE_PERSONA P, GE_EVENTO E
                  WHERE P.ID_PERSONA = E.ID_RESPONSABLE
                  AND E.CARGO_RESPONSABLE = 'Director');

--PRIMERO SACO LOS DIRECTORES, EL NOMBRE DE LOS DIRECTORES
SELECT P.NOMBRES
FROM GE_PERSONA P, GE_EVENTO E
WHERE P.ID_PERSONA = E.ID_RESPONSABLE
AND E.CARGO_RESPONSABLE = 'Director';

--PREGUNTA 4:

--PREGUNTA 5:

--PREGUNTA 6:

--PREGUNTA 7:


