CREATE TABLE CE_CLASE (
    ID_CLASE     NUMBER NOT NULL,
    CODIGO_CLASE VARCHAR2(20 BYTE) NOT NULL,
    NOMBRE       VARCHAR2(50 BYTE) NOT NULL,
    VIRTUAL      NUMBER(1) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN    DATE NOT NULL,
    COSTO        NUMBER(6, 2) NOT NULL
);

ALTER TABLE CE_CLASE ADD CONSTRAINT CE_CLASE_PK PRIMARY KEY ( ID_CLASE );

CREATE TABLE CE_HORARIO (
    ID_HORARIO  NUMBER NOT NULL,
    ID_CLASE    NUMBER NOT NULL,
    HORA_INICIO NUMBER NOT NULL,
    HORA_FIN    NUMBER NOT NULL,
    DNI_DOCENTE VARCHAR2(8 BYTE) NOT NULL
);

ALTER TABLE CE_HORARIO ADD CONSTRAINT CE_HORARIO_PK PRIMARY KEY ( ID_HORARIO );

CREATE TABLE CE_HORARIO_ALUMNO (
    ID_HORARIO NUMBER NOT NULL,
    DNI_ALUMNO VARCHAR2(8 BYTE) NOT NULL,
    NOTA_FINAL NUMBER
);

ALTER TABLE CE_HORARIO_ALUMNO ADD CONSTRAINT CE_HORARIO_ALUMNO_PK PRIMARY KEY ( ID_HORARIO,
                                                                                DNI_ALUMNO );

ALTER TABLE CE_HORARIO_ALUMNO
    ADD CONSTRAINT HOR_ALU_HOR_FK FOREIGN KEY ( ID_HORARIO )
        REFERENCES CE_HORARIO ( ID_HORARIO );

ALTER TABLE CE_HORARIO_ALUMNO
    ADD CONSTRAINT HOR_ALU_PER_FK FOREIGN KEY ( DNI_ALUMNO )
        REFERENCES CE_PERSONA ( DNI );

ALTER TABLE CE_HORARIO
    ADD CONSTRAINT HOR_CLA_FK FOREIGN KEY ( ID_CLASE )
        REFERENCES CE_CLASE ( ID_CLASE );

ALTER TABLE CE_HORARIO
    ADD CONSTRAINT HOR_PER_FK FOREIGN KEY ( DNI_DOCENTE )
        REFERENCES CE_PERSONA ( DNI );
