--LAB 2022-2

--PREGUNTA 1:
--PARTE A:
ALTER TABLE SP_INSUMO
RENAME COLUMN UNIDAD_DIVISORIA
TO ID_UNIDAD;

SELECT * FROM SP_INSUMO;
--PARTE B:
CREATE TABLE SP_DIMENSION(
    ID_DIMENSION CHAR (1 BYTE),
    DENOMINACION VARCHAR2 (40 BYTE),
    PRIMARY KEY (ID_DIMENSION)
);
--PARTE C:
CREATE TABLE SP_UNIDAD_DIVISORIA(
    ID_UNIDAD VARCHAR2 (5 BYTE),
    NOMBRE VARCHAR2 (50 BYTE),
    ID_DIMENSION CHAR (1 BYTE),
    PRIMARY KEY (ID_UNIDAD)
);
--ME PIDEN PONERLA COMO FOREIGN KEY
ALTER TABLE SP_UNIDAD_DIVISORIA
ADD CONSTRAINT FK_UNIDIV_DIMENSION
FOREIGN KEY (ID_DIMENSION)
REFERENCES SP_DIMENSION (ID_DIMENSION);
--PARTE D:
ALTER TABLE SP_INSUMO
ADD CONSTRAINT FK_INSUMO_ID_UNIDAD
FOREIGN KEY (ID_UNIDAD)
REFERENCES SP_UNIDAD_DIVISORIA(ID_UNIDAD);

--PREGUNTA 2:
--PARTE A:
ALTER TABLE SP_PRODUCTO
RENAME COLUMN TIPO
TO ID_TIPO;
--PARTE B:
CREATE TABLE SP_TIPO_PRODUCTO(
    ID_TIPO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2 (100 BYTE)
);
--PARTE C:
ALTER TABLE SP_PRODUCTO
ADD CONSTRAINT FK_PRODUCTO_TIPO
FOREIGN KEY (ID_TIPO)
REFERENCES SP_TIPO_PRODUCTO(ID_TIPO);

--PREGUNTA 3:
ALTER TABLE SP_COMPRA_INSUMO
RENAME TO SP_DETALLE_COMPRA;
ALTER TABLE SP_COMPRA_PRODUCTO
RENAME TO SP_DETALLE_PRODUCTO;

--PREGUNTA 4:
ALTER TABLE SP_INSUMO
MODIFY ESTADO CHAR (1 BYTE);

ALTER TABLE SP_MATRIZ_INSUMO
MODIFY CANTIDAD NUMERIC(6,2);

ALTER TABLE SP_DETALLE_COMPRA
MODIFY CANTIDAD NUMERIC(6,2);

ALTER TABLE SP_ORDEN_COMPRA
MODIFY FECHA_AUTORIZACION NULL;

ALTER TABLE SP_ORDEN_COMPRA
MODIFY FECHA_ENTREGA NULL;

ALTER TABLE SP_ORDEN_PRODUCCION
MODIFY FECHA_AUTORIZACION NULL;

ALTER TABLE SP_ORDEN_PRODUCCION
MODIFY FECHA_FIN NULL;

ALTER TABLE SP_DETALLE_PRODUCTO 
MODIFY MERMA DEFAULT (0);

--PREGUNTA 5:
ALTER TABLE SP_PRODUCTO
ADD STOCK NUMERIC NOT NULL;

--EJECUTAR DML
--PREGUNTA 6:
SELECT * FROM SP_INSUMO;
SELECT * FROM SP_UNIDAD_DIVISORIA;

--PARA UNIR TABLAS
SELECT A.ID_INSUMO, A.NOMBRE, A.STOCK
FROM SP_INSUMO A, SP_UNIDAD_DIVISORIA B
WHERE b.id_unidad = a.id_unidad
AND B.NOMBRE = 'Pulgada cuadrada';

--PREGUNTA 6:
SELECT * FROM SP_MATRIZ_INSUMO;
SELECT * FROM SP_PRODUCTO;
SELECT * FROM SP_INSUMO;

SELECT C.NOMBRE AS INSUMO, (A.CANTIDAD||' '||D.NOMBRE||' ('||C.ID_UNIDAD||')') AS REQUERIMIENTO
FROM SP_MATRIZ_INSUMO A, SP_PRODUCTO B, SP_INSUMO C, SP_UNIDAD_DIVISORIA D
WHERE b.id_producto = a.id_producto 
AND c.id_insumo = a.id_insumo
AND d.id_unidad = c.id_unidad
AND B.NOMBRE = 'Mocasín Caballero Talla 41';
