-- ALEX CALERO REVILLA - 20206455

-- PREGUNTA 1
-- INCISO A
CREATE TABLE HE_CLIENTE (
    ID_CLIENTE NUMBER NOT NULL,
    NOMBRES VARCHAR2(50 BYTE) NOT NULL,
    APELLIDOS VARCHAR2(50 BYTE) NOT NULL,
    DNI VARCHAR2(8 BYTE) NOT NULL,
    CONSTRAINT CLIENTE_PK PRIMARY KEY (ID_CLIENTE)
);
-- INCISO B
COMMENT ON COLUMN HE_CLIENTE.ID_CLIENTE IS 'Identificador del cliente.';
COMMENT ON COLUMN HE_CLIENTE.NOMBRES IS 'Nombres del cliente.';
COMMENT ON COLUMN HE_CLIENTE.APELLIDOS IS 'Apellidos del cliente.';
COMMENT ON COLUMN HE_CLIENTE.DNI IS 'DNI del cliente.';

-- PREGUNTA 2
-- INCISO A
ALTER TABLE HE_PEDIDO ADD ID_CLIENTE NUMBER NOT NULL;
-- INCISO B
ALTER TABLE HE_PEDIDO ADD CONSTRAINT PEDIDO_FK FOREIGN KEY (ID_CLIENTE)
REFERENCES HE_CLIENTE (ID_CLIENTE);

-- PREGUNTA 3
INSERT INTO HE_CLIENTE (ID_CLIENTE, NOMBRES, APELLIDOS, DNI)
VALUES (1, 'Alex Ismael', 'Calero Revilla', '71461660');

INSERT INTO HE_PEDIDO (ID_PEDIDO, ID_CLIENTE, PRECIO)
VALUES (1, 1, 0.0);

INSERT INTO HE_PEDIDO_POSTRE (ID_PEDIDO_POSTRE, ID_PEDIDO, ID_POSTRE, ID_COMPLEMENTO_POSTRE)
VALUES (1, 1, 6, 2);
INSERT INTO HE_PEDIDO_POSTRE (ID_PEDIDO_POSTRE, ID_PEDIDO, ID_POSTRE, ID_COMPLEMENTO_POSTRE)
VALUES (2, 1, 8, 3);

INSERT INTO HE_PEDIDO_POSTRE_SABOR (ID_PEDIDO_POSTRE_SABOR, ID_PEDIDO_POSTRE, ID_SABOR, NUMERO_BOLAS)
VALUES (1, 1, 2, 2);
INSERT INTO HE_PEDIDO_POSTRE_SABOR (ID_PEDIDO_POSTRE_SABOR, ID_PEDIDO_POSTRE, ID_SABOR, NUMERO_BOLAS)
VALUES (2, 1, 3, 1);
INSERT INTO HE_PEDIDO_POSTRE_SABOR (ID_PEDIDO_POSTRE_SABOR, ID_PEDIDO_POSTRE, ID_SABOR, NUMERO_BOLAS)
VALUES (3, 2, 8, 2);

-- PREGUNTA 4
SELECT P.ID_PEDIDO_POSTRE, S.ID_SABOR, S.NOMBRE, P.NUMERO_BOLAS
FROM HE_PEDIDO_POSTRE_SABOR P, HE_SABOR S
WHERE P.ID_SABOR = S.ID_SABOR
ORDER BY 2;

-- PREGUNTA 5
-- INCISO A
UPDATE HE_PEDIDO SET PRECIO = 8.0 WHERE ID_PEDIDO = 1;
-- INCISO B
SELECT P.ID_PEDIDO, C.NOMBRES||' '||C.APELLIDOS AS NOMBRE_COMPLETO, P.PRECIO
FROM HE_PEDIDO P, HE_CLIENTE C;

-- PREGUNTA 6
UPDATE HE_ORDEN_PRODUCCION SET FECHA_HORA_TERM_REAL = SYSDATE, ESTADO = 'T'
WHERE FECHA_HORA_TERM_PLANIF < TO_DATE('27/01/2023', 'DD/MM/YYYY');

-- PREGUNTA 7
SELECT OP.ID_ORDEN_PRODUCCION AS ID_ORDEN, OP.ID_SABOR, S.NOMBRE AS NOMBRE_SABOR,
OP.CANTIDAD, TO_CHAR(OP.FECHA_HORA_REGISTRO,'DD-MM-YYYY') AS FECHA_REGISTRO,
TO_CHAR(OP.FECHA_HORA_TERM_PLANIF, 'DD-MM-YYYY') AS FECHA_PLANIFICADA,
TO_CHAR(OP.FECHA_HORA_TERM_REAL, 'DD-MM-YYYY') AS FECHA_TERMINADA, OP.ESTADO
FROM HE_ORDEN_PRODUCCION OP, HE_SABOR S WHERE OP.ID_SABOR = S.ID_SABOR
ORDER BY FECHA_REGISTRO, CANTIDAD DESC;
