--PARTE 2 DE EXAMEN 2022.1

--B) LISTADO QUE DEVUELVA LAS CANTIDADES (COUNT) DE PRODUCTOS POR ALMACEN
-- CUYA DESCRIPCION DE LA UNIDAD DE MEDIDA ES LATA
SELECT * FROM X99_ALMACEN; --DESCRIPCION(NOMBRE ALMACEN)
SELECT * FROM X99_ARTICULOXALMACEN; --ID_ALMACEN + ID_ARTICULO
SELECT * FROM X99_UNIDAD_MEDIDA; --DESCRIPCION_CORTA (LATA)
SELECT * FROM X99_ARTICULO; -- DESCRIPCION
 
SELECT A.DESCRIPCION AS ALMACEN, U.DESCRIPCION_CORTA, COUNT(*) AS CANTIDAD
FROM X99_ALMACEN A, X99_UNIDAD_MEDIDA U, X99_ARTICULOXALMACEN AM
WHERE am.id_almacen = a.id_almacen
GROUP BY A.DESCRIPCION , U.DESCRIPCION_CORTA
HAVING U.DESCRIPCION_CORTA = 'LATA';

--C) LISTADO DONDE APAREZCAN TODOS LOS PRODUCTOS CUYO COSTO ES MAYOR AL COSTO PROMEDIO DE TODOS LOS PRODUCTOS
SELECT * FROM X99_ARTICULO; --CODIGO + COSTO
SELECT * FROM X99_SUBGRUPO; -- ID_SUBGRUPO + ID_GRUPO
SELECT * FROM X99_GRUPO; -- ID_GRUPO
--PRIMERO SACO EL COSTO PROMEDIO DE TODOS LOS PRODUCTOS -> AVG(COSTO)
SELECT AVG(COSTO)
FROM X99_ARTICULO;

--AHORA APLICO SUBCONSULTA QUE ME GENERE EL COSTO MAYOR
SELECT G.ID_GRUPO AS GRUPO, S.ID_SUBGRUPO AS SUBGRUPO, A.CODIGO,A.DESCRIPCION, A.COSTO
FROM X99_ARTICULO A, X99_SUBGRUPO S, X99_GRUPO G
WHERE A.ID_SUBGRUPO = S.ID_SUBGRUPO AND S.ID_GRUPO = G.ID_GRUPO
AND COSTO > (SELECT AVG(COSTO) FROM X99_ARTICULO);
