--LAB3 DIRIGIDO - 2020.2

--PREGUNTA 1: MOSTRAR CANTIDAD DE PROD, SUMA PRECIOS, PRECIO PROM, PRECIO MAX, PRECIO MIN
SELECT * FROM PRODUCTO;
SELECT COUNT(*) AS CANT_PROD, SUM(PRECIO) , AVG(PRECIO), MAX(PRECIO), MIN(PRECIO)
FROM PRODUCTO;

--PREGUNTA 2: MOSTRAR CANTIDAD DE CLIENTES VARONES Y CLIENTES MUJERES(2 INTEMS DE UNA COLUMNA)
SELECT * FROM CLIENTE;
SELECT SEXO, COUNT(*) AS CANT
FROM CLIENTE
GROUP BY SEXO;

--PREGUNTA 3: MOSTRAR TODAS LAS FECHAS Y LA CANTIDAD DE VENTAS QUE SE HICIERON EN CADA UNA DE ELLAS (GROUP)
SELECT * FROM VENTA;
SELECT FECHA_VENTA, COUNT(*) AS CANT
FROM VENTA
GROUP BY FECHA_VENTA;

--PREGUNTA 4: MOSTRAR LAS FECHAS EN LAS QUE SOLO SE REALIZO UNA VENTA
SELECT * FROM VENTA;
SELECT FECHA_VENTA, COUNT(*) AS CANT
FROM VENTA
GROUP BY FECHA_VENTA
HAVING COUNT(*) = 1;

--PREGUNTA 5: MOSTRAR LA CANTIDAD DE VENTAS QUE SE REALIZO A CADA CLIENTE (PARA -> GROUP)
SELECT * FROM CLIENTE;
SELECT * FROM VENTA;
SELECT C.APE_PATERNO||' '||C.APE_MATERNO||' '||C.NOMBRE AS CLIENTE, COUNT(*) AS CANT
FROM CLIENTE C, VENTA V
WHERE v.id_cliente = c.id_cliente 
GROUP BY C.APE_PATERNO||' '||C.APE_MATERNO||' '||C.NOMBRE;

--PREGUNTA 6: MOSTRAR EL TOTAL EN VENTAS REALIZAS EL 17 DE OCTUBRE DEL 2020
SELECT * FROM VENTA;
SELECT * FROM DETALLE_VENTA;
SELECT SUM(TOTAL) AS TOTAL_VENDIDO_17_OCTUBRE_2020
FROM VENTA V, DETALLE_VENTA DV
WHERE v.id_venta = dv.id_venta
AND v.fecha_venta = '17/10/2020';

--PREGUNTA 7: MOSTRAR LA CANTIDAD DE UNIDADES QUE SE VENDIERON DE CADA PRODUCTO (PARA -> GROUP)
SELECT * FROM PRODUCTO;
SELECT * FROM DETALLE_VENTA;
SELECT P.NOMBRE AS NOMBRE_PRODUCTO , SUM(CANTIDAD) AS CANT
FROM PRODUCTO P, DETALLE_VENTA DV
WHERE p.id_producto = dv.id_producto
GROUP BY NOMBRE;

--PREGUNTA 8: MOSTRAR EL PRODUCTO QUE TIENE EL MENOR PRECIO
SELECT * FROM PRODUCTO;
SELECT NOMBRE, PRECIO
FROM PRODUCTO
WHERE PRECIO = (SELECT MIN(PRECIO) FROM PRODUCTO);

--PREGUNTA 9: MOSTRAR EL PROMEDIO DEL PAGO REALIZADO X CADA CLIENTE EN LOS PROD QUE ADQUIRIO, EXCEPTO ""
SELECT * FROM CLIENTE;
SELECT * FROM VENTA;
SELECT * FROM DETALLE_VENTA;
SELECT C.APE_PATERNO||' '||C.APE_MATERNO||' '||C.NOMBRE AS CLIENTE, ROUND(AVG(TOTAL),2) AS PAGO_PROM_PRODUCTO
FROM CLIENTE C, VENTA V, DETALLE_VENTA DV
WHERE v.id_cliente = c.id_cliente AND v.id_venta = dv.id_venta
GROUP BY C.APE_PATERNO||' '||C.APE_MATERNO||' '||C.NOMBRE
--COMO ME PIDEN ELIMINAR UNO, TIENE QUE SER DEL GRUPO QUE CREE, PARA ELLO SE USA HAVING => <> (diferente)
HAVING C.APE_PATERNO||' '||C.APE_MATERNO||' '||C.NOMBRE <> 'Peralta Gutierrez Maria';

--PREGUNTA 10: MOSTRAR APELLIDOS, NOMBRE Y FECHA DE NAC DEL CLIENTE MÁS JOVEN
SELECT * FROM CLIENTE;
SELECT APE_PATERNO, APE_MATERNO, NOMBRE, FECHA_NACIMIENTO
FROM CLIENTE
WHERE FECHA_NACIMIENTO IN (SELECT MAX(FECHA_NACIMIENTO) FROM CLIENTE);

--PREGUNTA 11: MOSTRAR AP, NOMBRE Y FECHA DE VENTA DE LOS CLIENTES QUE COMPRARON LOS MISMO DIAS QUE EL CLIENTE " "
SELECT * FROM CLIENTE;
SELECT * FROM VENTA;
SELECT C.APE_PATERNO, C.APE_MATERNO, C.NOMBRE, V.FECHA_VENTA
FROM CLIENTE C, VENTA V
WHERE c.id_cliente=v.id_cliente
AND FECHA_VENTA in (SELECT FECHA_VENTA
                   FROM CLIENTE C, VENTA V
                   WHERE c.id_cliente= v.id_cliente
                   AND c.ape_paterno = 'Cuba' AND c.ape_materno = 'Linares');
                   
SELECT FECHA_VENTA
FROM VENTA V, CLIENTE C
WHERE v.id_cliente = c.id_cliente
AND c.ape_paterno = 'Cuba' AND c.ape_materno = 'Linares';