--L1 2021-2
--PREGUNTA 1
CREATE TABLE PP_PROMOCION(
    ID_PROMOCION NUMBER NOT NULL,
    NOMBRE VARCHAR2 (100 BYTE) NOT NULL,
    FECHA_INICIO DATE NOT NULL,
    FECHA_FIN DATE NOT NULL,
    PRIMARY KEY (ID_PROMOCION)
);

COMMENT ON COLUMN PP_PROMOCION.ID_PROMOCION IS
    'IDENTIFICADOR DE LA PROMOCION';
COMMENT ON COLUMN PP_PROMOCION.NOMBRE IS
    'NOMBRE DE LA PROMOCION';
COMMENT ON COLUMN PP_PROMOCION.FECHA_INICIO IS
    'FECHA DE INICIO DE LA PROMOCION';
COMMENT ON COLUMN PP_PROMOCION.FECHA_FIN IS
    'FECHA DE FIN DE LA PROMOCION.';
--PARA VISUALIZAR QUE TIPO DE DATOS ESTA GUARDANDO
DESC PP_PROMOCION;

--PREGUNTA 2: AGREGAR DATOS A LAS COLUMNAS
ALTER TABLE PP_PROMOCION
ADD TASA_DESCUENTO NUMBER(2,2);
ALTER TABLE PP_TARJETA_BANCARIA
ADD COMPRAS_INTERNET VARCHAR2(50);

COMMENT ON COLUMN PP_PROMOCION.TASA_DESCUENTO IS
    'PORCENTAJE DE DESCUENTO A APLICAR CON LA PROMOCION';
COMMENT ON COLUMN PP_TARJETA_BANCARIA.COMPRAS_INTERNET IS
    'INDICA SI LA TARJETA ESTÁ HABILITADA PARA REALIZAR COMPRAS POR INTERNET. (A o I)';
    
--PREGUNTA 3: MODIFICAR VALORES EN UNA TABLA
ALTER TABLE PP_PROMOCION 
MODIFY TASA_DESCUENTO NUMBER(6,3);
ALTER TABLE PP_TARJETA_BANCARIA
MODIFY COMPRAS_INTERNET CHAR(1 BYTE);

--PREGUNTA 4: MODIFICAR COLUMNA PARA QUE ACEPTE NULOS
ALTER TABLE PP_CLIENTE
MODIFY FECHA_NACIMIENTO NULL;

--VERIFICAMOS LOS CAMBIOS
DESC PP_CLIENTE;

--PREGUNTA 5: AGREGAR REGIONES
insert into pp_region values (110000, 'ICA');
insert into pp_provincia values (110100, 'ICA',110000);
insert into pp_distrito values (110101, 'ICA',110100);
insert into pp_distrito values (110102, 'LA TINGUIÑA',110100);
insert into pp_distrito values (110103, 'LOS AQUIJES',110100);
insert into pp_distrito values (110104, 'OCUCAJE',110100);
insert into pp_distrito values (110105, 'PACHACUTEC',110100);
insert into pp_distrito values (110106, 'PARCONA',110100);
insert into pp_distrito values (110107, 'PUEBLO NUEVO',110100);
insert into pp_distrito values (110108, 'SALAS',110100);
insert into pp_distrito values (110109, 'SAN JOSE DE LOS MOLINOS',110100);
insert into pp_distrito values (110110, 'SAN JUAN BAUTISTA',110100);
insert into pp_distrito values (110111, 'SANTIAGO',110100);
insert into pp_distrito values (110112, 'SUBTANJALLA',110100);
insert into pp_distrito values (110113, 'TATE',110100);
insert into pp_distrito values (110114, 'YAUCA DEL ROSARIO',110100);
--PARA SABER COMO GUARDARLO
DESC PP_REGION;
DESC PP_PROVINCIA;
DESC PP_DISTRITO;
--VERIFICAMOS QUE LO GUARDAMOS
select * from pp_region;
select * from pp_provincia;
select * from pp_distrito;

--PREGUNTA 6:
DESC PP_TARJETA_BANCARIA; --EN ESTA TABLA REALIZARÉ LOS CAMBIOS
SELECT NUMERO_TARJETA, UBICACION, FECHA_VENCIMIENTO, COMPRAS_INTERNET
FROM PP_TARJETA_BANCARIA
WHERE UBICACION LIKE 'A' AND COMPRAS_INTERNET LIKE 'A'
ORDER BY FECHA_VENCIMIENTO ASC;

--PREGUNTA 7: LISTAR LOS CLIENTES EN "APELLIDOS, NOMBRES"
--NOMBRES || NUMERO_DOCUMENTO || NUMERO_CUENTA || NUMERO_TARJETA--
SELECT ( a.apellido_paterno ||' '||a.apellido_materno||', '||a.nombres) as NOMBRES ,
a.numero_documento,
b.numero_cuenta,
c.numero_tarjeta
FROM PP_CLIENTE A, PP_CUENTA_BANCARIA B, PP_TARJETA_BANCARIA C
WHERE c.id_cuenta = b.id_cuenta
AND b.id_cliente = a.id_cliente
AND c.estado = 'V'
AND c.ubicacion = 'A'
AND c.fecha_emision>to_date('01/05/2016','DD/MM/YYYY')
order by a.apellido_paterno asc;

--PREGUNTA 8: ANULAR TODAS LAS TARJETAS QUE A LA FECHA ACTUAL HAYAN VENCIDO
UPDATE PP_TARJETA_BANCARIA
SET ESTADO = 'A'
WHERE FECHA_VENCIMIENTO<TO_DATE('27/09/2021','DD/MM/YYYY');

--PARA VERIFICAR QUE TARJETAS VA A ANULAR
SELECT * FROM PP_TARJETA_BANCARIA
WHERE FECHA_VENCIMIENTO<TO_DATE('27/09/2021','DD/MM/YYYY');

--PREGUNTA 9:
SELECT A.NUMERO_CUENTA , B.MONTO_TRANSFERIDO, C.NOMBRES, C.APELLIDO_PATERNO
FROM PP_CUENTA_BANCARIA A, PP_TRANSFERENCIA B, PP_CLIENTE C
WHERE c.id_cliente = a.id_cliente
AND B.CUENTA_DESTINO = A.ID_CUENTA
AND B.MONTO_TRANSFERIDO>500 ;

--PREGUNTA 10:
DELETE FROM PP_TARJETA_BANCARIA
WHERE ESTADO = 'A';

DELETE FROM PP_TARJETA_BANCARIA
WHERE UBICACION = 'V';

DELETE FROM PP_TARJETA_BANCARIA
WHERE UBICACION = 'F';

SELECT * FROM PP_TARJETA_BANCARIA;
